# ***Online News Popularity Project***

##### ***Name*** : _Allen Daniel Raju_
##### ***Batch*** :  _DSML - D53_ 
##### ***Organization*** : _Entri Elevate Coding_
##### ***Date*** : _18-04-2025_

### Modeling

In [1]:
%matplotlib inline

In [2]:
import numpy as np
import scipy as sp
import scipy.stats as stats
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge, Lasso
from sklearn.linear_model import RidgeCV, LassoCV
from sklearn.ensemble import RandomForestRegressor
import statsmodels.formula.api as smf
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [3]:
# Load dataset
df = pd.read_csv('df_cleaned.csv')

#### Simple Linear Regression

In [4]:
df.head()

,n_tokens_title,n_tokens_content,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,num_keywords,kw_min_min,...,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares,data_channel,weekday_is
0,12.0,219.0,0.815385,4.0,2.0,1.0,0.0,4.680365,5.0,0.0,...,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,593,2,1
1,9.0,255.0,0.791946,3.0,1.0,1.0,0.0,4.913725,4.0,0.0,...,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,711,3,1
2,9.0,211.0,0.663866,3.0,1.0,1.0,0.0,4.393365,6.0,0.0,...,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1500,3,1
3,9.0,531.0,0.665635,9.0,0.0,1.0,0.0,4.404896,7.0,0.0,...,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000,1200,2,1
4,13.0,1072.0,0.540890,19.0,19.0,20.0,0.0,4.682836,7.0,0.0,...,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,505,5,1

In [5]:
df.columns

Index(['n_tokens_title', 'n_tokens_content', 'n_non_stop_unique_tokens',
       'num_hrefs', 'num_self_hrefs', 'num_imgs', 'num_videos',
       'average_token_length', 'num_keywords', 'kw_min_min', 'kw_max_min',
       'kw_min_max', 'kw_max_max', 'kw_avg_max', 'kw_min_avg', 'kw_max_avg',
       'self_reference_min_shares', 'self_reference_max_shares',
       'self_reference_avg_sharess', 'LDA_00', 'LDA_01', 'LDA_02', 'LDA_03',
       'LDA_04', 'global_subjectivity', 'global_sentiment_polarity',
       'global_rate_positive_words', 'global_rate_negative_words',
       'rate_positive_words', 'rate_negative_words', 'avg_positive_polarity',
       'min_positive_polarity', 'max_positive_polarity',
       'avg_negative_polarity', 'min_negative_polarity',
       'max_negative_polarity', 'title_subjectivity',
       'title_sentiment_polarity', 'abs_title_subjectivity',
       'abs_title_sentiment_polarity', 'shares', 'data_channel', 'weekday_is'],
      dtype='object')

In [6]:
# Predictors in the dataset
predictors = ['n_tokens_title', 'n_tokens_content', 'n_non_stop_unique_tokens',
       'num_hrefs', 'num_self_hrefs', 'num_imgs', 'num_videos',
       'average_token_length', 'num_keywords', 'kw_min_min', 'kw_max_min',
       'kw_min_max', 'kw_max_max', 'kw_avg_max', 'kw_min_avg', 'kw_max_avg',
       'self_reference_min_shares', 'self_reference_max_shares',
       'self_reference_avg_sharess', 'LDA_00', 'LDA_01', 'LDA_02', 'LDA_03',
       'LDA_04', 'global_subjectivity', 'global_sentiment_polarity',
       'global_rate_positive_words', 'global_rate_negative_words',
       'rate_positive_words', 'rate_negative_words', 'avg_positive_polarity',
       'min_positive_polarity', 'max_positive_polarity',
       'avg_negative_polarity', 'min_negative_polarity',
       'max_negative_polarity', 'title_subjectivity',
       'title_sentiment_polarity', 'abs_title_subjectivity',
       'abs_title_sentiment_polarity', 'data_channel', 'weekday_is']

In [7]:
# Extract features (X) and target (y)
X = df[predictors]
y = df['shares']

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [8]:
# Shape of train and test datasets
print(X_train.shape)
print(X_test.shape)

(25756, 42)
(12687, 42)

In [9]:
# Print shape of y objects
print(y_train.shape)
print(y_test.shape)

(25756,)
(12687,)

In [10]:
# Create DataFrame with training dataset
x_df_train = pd.DataFrame(data=X_train, columns=predictors)
x_df_train.head()

,n_tokens_title,n_tokens_content,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,num_keywords,kw_min_min,...,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,data_channel,weekday_is
35308,12.0,294.0,0.820359,7.0,5.0,2.0,1.0,4.625850,7.0,-1.0,...,1.0,-0.332143,-0.400000,-0.1250,0.00000,0.000000,0.50000,0.000000,2,3
2595,11.0,284.0,0.762500,1.0,0.0,1.0,1.0,4.690141,5.0,217.0,...,0.8,-0.194444,-0.300000,-0.1000,0.60000,0.200000,0.10000,0.200000,3,4
6100,10.0,254.0,0.745455,7.0,5.0,1.0,0.0,4.748031,6.0,4.0,...,0.7,-0.133333,-0.166667,-0.1000,0.00000,0.000000,0.50000,0.000000,3,2
11827,9.0,292.0,0.750000,6.0,5.0,0.0,17.0,4.602740,5.0,4.0,...,1.0,-0.475000,-0.700000,-0.2000,0.49513,0.211039,0.00487,0.211039,4,4
12758,11.0,306.0,0.741573,15.0,2.0,15.0,0.0,4.205882,10.0,4.0,...,1.0,-0.473438,-1.000000,-0.1875,0.00000,0.000000,0.50000,0.000000,7,3

In [11]:
# Training series with shares
y_df_train = pd.DataFrame(data=y_train, columns=['shares']) 
y_df_train.head()

       shares
35308    1400
2595     2300
6100      968
11827    1500
12758   74100

In [12]:
# Concatenate x and y together to create dataframe of training set
train_df = pd.concat([x_df_train, y_df_train], axis=1, sort=False)
train_df.head()

,n_tokens_title,n_tokens_content,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,num_keywords,kw_min_min,...,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,data_channel,weekday_is,shares
35308,12.0,294.0,0.820359,7.0,5.0,2.0,1.0,4.625850,7.0,-1.0,...,-0.332143,-0.400000,-0.1250,0.00000,0.000000,0.50000,0.000000,2,3,1400
2595,11.0,284.0,0.762500,1.0,0.0,1.0,1.0,4.690141,5.0,217.0,...,-0.194444,-0.300000,-0.1000,0.60000,0.200000,0.10000,0.200000,3,4,2300
6100,10.0,254.0,0.745455,7.0,5.0,1.0,0.0,4.748031,6.0,4.0,...,-0.133333,-0.166667,-0.1000,0.00000,0.000000,0.50000,0.000000,3,2,968
11827,9.0,292.0,0.750000,6.0,5.0,0.0,17.0,4.602740,5.0,4.0,...,-0.475000,-0.700000,-0.2000,0.49513,0.211039,0.00487,0.211039,4,4,1500
12758,11.0,306.0,0.741573,15.0,2.0,15.0,0.0,4.205882,10.0,4.0,...,-0.473438,-1.000000,-0.1875,0.00000,0.000000,0.50000,0.000000,7,3,74100

In [13]:
# Create DataFrame with test dataset
x_df_test = pd.DataFrame(data=X_test, columns=predictors)
x_df_test.head()

,n_tokens_title,n_tokens_content,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,num_keywords,kw_min_min,...,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,data_channel,weekday_is
5532,9.0,218.0,0.843750,2.0,1.0,0.0,1.0,4.353211,7.0,4.0,...,0.6,-0.409524,-0.666667,-0.071429,0.0,0.0000,0.5,0.0000,2,4
15242,11.0,268.0,0.835616,5.0,3.0,1.0,0.0,4.492537,4.0,4.0,...,0.6,-0.118750,-0.187500,-0.050000,0.1,0.3000,0.4,0.3000,6,3
35329,14.0,851.0,0.633858,15.0,6.0,1.0,0.0,4.584019,7.0,-1.0,...,0.8,-0.307568,-0.800000,-0.050000,0.7,0.1125,0.2,0.1125,5,3
9288,9.0,725.0,0.536748,19.0,6.0,1.0,0.0,4.590345,10.0,4.0,...,1.0,-0.246875,-0.500000,-0.100000,0.9,-0.6000,0.4,0.6000,6,3
14634,8.0,616.0,0.753846,10.0,0.0,1.0,0.0,4.683442,7.0,4.0,...,1.0,-0.337976,-0.625000,-0.071429,0.0,0.0000,0.5,0.0000,2,5

In [14]:
# Test series with shares
y_df_test = pd.DataFrame(data=y_test, columns=['shares']) 
y_df_test.head()

       shares
5532     1500
15242    1100
35329    1600
9288     9500
14634     682

In [15]:
# Concatenate x and y together to create dataframe of test set
test_df = pd.concat([x_df_test, y_df_test], axis=1, sort=False)
test_df.head()

,n_tokens_title,n_tokens_content,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,num_keywords,kw_min_min,...,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,data_channel,weekday_is,shares
5532,9.0,218.0,0.843750,2.0,1.0,0.0,1.0,4.353211,7.0,4.0,...,-0.409524,-0.666667,-0.071429,0.0,0.0000,0.5,0.0000,2,4,1500
15242,11.0,268.0,0.835616,5.0,3.0,1.0,0.0,4.492537,4.0,4.0,...,-0.118750,-0.187500,-0.050000,0.1,0.3000,0.4,0.3000,6,3,1100
35329,14.0,851.0,0.633858,15.0,6.0,1.0,0.0,4.584019,7.0,-1.0,...,-0.307568,-0.800000,-0.050000,0.7,0.1125,0.2,0.1125,5,3,1600
9288,9.0,725.0,0.536748,19.0,6.0,1.0,0.0,4.590345,10.0,4.0,...,-0.246875,-0.500000,-0.100000,0.9,-0.6000,0.4,0.6000,6,3,9500
14634,8.0,616.0,0.753846,10.0,0.0,1.0,0.0,4.683442,7.0,4.0,...,-0.337976,-0.625000,-0.071429,0.0,0.0000,0.5,0.0000,2,5,682

In [16]:
# Use Statsmodel to create simple linear regression model of shares based on a single predictor 
# train model on the training set 

# Loop through predictors and fit linear models
for i in predictors:
    lin_model = smf.ols(formula=f'shares ~ {i}', data=train_df).fit()
    print(f"Dependent variable: {i}")
    print(f"R-squared: {lin_model.rsquared}")
    print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
    print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
    print()

Dependent variable: n_tokens_title
R-squared: 0.0001515237439502215
Coefficient 0 (Intercept): 2763.7066860373816
Coefficient 1 (n_tokens_title): 41.38297036208207

Dependent variable: n_tokens_content
R-squared: 1.616089151390554e-07
Coefficient 0 (Intercept): 3189.8210198786023
Coefficient 1 (n_tokens_content): 0.006101657911188135

Dependent variable: n_non_stop_unique_tokens
R-squared: 4.6289012812783525e-06
Coefficient 0 (Intercept): 3190.562721499027
Coefficient 1 (n_non_stop_unique_tokens): 3.754671787264772

Dependent variable: num_hrefs
R-squared: 0.006000091722709655
Coefficient 0 (Intercept): 2651.9294168788856
Coefficient 1 (num_hrefs): 48.15881586146109

Dependent variable: num_self_hrefs
R-squared: 8.405814721945681e-06
Coefficient 0 (Intercept): 3175.4156501004063
Coefficient 1 (num_self_hrefs): 5.250899905331114

Dependent variable: num_imgs
R-squared: 0.004309108074239676
Coefficient 0 (Intercept): 2937.6890883089864
Coefficient 1 (num_imgs): 56.208635118981945

Dependent variable: num_videos
R-squared: 0.0011591765981108226
Coefficient 0 (Intercept): 3120.828443128101
Coefficient 1 (num_videos): 58.40043885525708

Dependent variable: average_token_length
R-squared: 0.00032622120829983725
Coefficient 0 (Intercept): 5293.431183682375
Coefficient 1 (average_token_length): -447.88645511163463

Dependent variable: num_keywords
R-squared: 0.0015970330294006185
Coefficient 0 (Intercept): 2128.791970750539
Coefficient 1 (num_keywords): 147.56600158968484

Dependent variable: kw_min_min
R-squared: 7.82127676890454e-06
Coefficient 0 (Intercept): 3200.719024648004
Coefficient 1 (kw_min_min): -0.2821690721966581

Dependent variable: kw_max_min
R-squared: 0.0007584718375283073
Coefficient 0 (Intercept): 3132.0645465967455
Coefficient 1 (kw_max_min): 0.05298706923717653

Dependent variable: kw_min_max
R-squared: 1.4247178282578155e-05
Coefficient 0 (Intercept): 3187.1073244608324
Coefficient 1 (kw_min_max): 0.0004680876672044067

C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")

Dependent variable: kw_max_max
R-squared: 0.0001585300416966362
Coefficient 0 (Intercept): 2883.638381215238
Coefficient 1 (kw_max_max): 0.00041209459525493183

Dependent variable: kw_avg_max
R-squared: 0.002761497059635354
Coefficient 0 (Intercept): 2473.559085330373
Coefficient 1 (kw_avg_max): 0.002822519902888512

Dependent variable: kw_min_avg
R-squared: 0.0022968557146618718
Coefficient 0 (Intercept): 2861.6449487364825
Coefficient 1 (kw_min_avg): 0.3007999101907428

Dependent variable: kw_max_avg
R-squared: 0.008831122613249698
Coefficient 0 (Intercept): 2543.359809775412
Coefficient 1 (kw_max_avg): 0.11638521701139698

Dependent variable: self_reference_min_shares
R-squared: 0.0038962366980352936
Coefficient 0 (Intercept): 3100.1047212012836
Coefficient 1 (self_reference_min_shares): 0.022840463860789178

Dependent variable: self_reference_max_shares
R-squared: 0.0033943264041189636
Coefficient 0 (Intercept): 3089.086281614372
Coefficient 1 (self_reference_max_shares): 0.009628639269546522

Dependent variable: self_reference_avg_sharess
R-squared: 0.004454717811233966
Coefficient 0 (Intercept): 3065.7317523739985
Coefficient 1 (self_reference_avg_sharess): 0.019182778292383434

Dependent variable: LDA_00
R-squared: 9.616717046823098e-05
Coefficient 0 (Intercept): 3242.5564773395904
Coefficient 1 (LDA_00): -259.1767680971474

Dependent variable: LDA_01
R-squared: 9.513129292648692e-05
Coefficient 0 (Intercept): 3237.375668593334
Coefficient 1 (LDA_01): -314.234887264788

Dependent variable: LDA_02
R-squared: 0.0070807483161247076
Coefficient 0 (Intercept): 3651.5914491730136
Coefficient 1 (LDA_02): -2103.0231335838753

Dependent variable: LDA_03
R-squared: 0.013603114235128722
Coefficient 0 (Intercept): 2583.0181155808
Coefficient 1 (LDA_03): 2861.2087497073226

Dependent variable: LDA_04
R-squared: 0.00030134743968723843
Coefficient 0 (Intercept): 3293.5306911090643
Coefficient 1 (LDA_04): -421.0496736374714

C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")

Dependent variable: global_subjectivity
R-squared: 0.009733678847423155
Coefficient 0 (Intercept): -430.4446250680072
Coefficient 1 (global_subjectivity): 7936.358317846327

Dependent variable: global_sentiment_polarity
R-squared: 0.00022116305101993472
Coefficient 0 (Intercept): 3057.9778371680495
Coefficient 1 (global_sentiment_polarity): 1097.6511014259922

Dependent variable: global_rate_positive_words
R-squared: 0.00023226595455005938
Coefficient 0 (Intercept): 2920.383741535202
Coefficient 1 (global_rate_positive_words): 6681.068935942345

Dependent variable: global_rate_negative_words
R-squared: 0.0005961799695456405
Coefficient 0 (Intercept): 2913.3725985746023
Coefficient 1 (global_rate_negative_words): 16352.290089652484

Dependent variable: rate_positive_words
R-squared: 8.418653993780278e-05
Coefficient 0 (Intercept): 3498.0439720167215
Coefficient 1 (rate_positive_words): -433.3180358208961

Dependent variable: rate_negative_words
R-squared: 8.583326579880701e-05
Coefficient 0 (Intercept): 3063.359234166649
Coefficient 1 (rate_negative_words): 438.1549117441433

Dependent variable: avg_positive_polarity
R-squared: 0.002720789995647732
Coefficient 0 (Intercept): 1620.7102624087793
Coefficient 1 (avg_positive_polarity): 4307.703442436068

Dependent variable: min_positive_polarity
R-squared: 0.00030858494868690745
Coefficient 0 (Intercept): 3020.7416994383507
Coefficient 1 (min_positive_polarity): 1750.586340519088

Dependent variable: max_positive_polarity
R-squared: 0.0013075524026637808
Coefficient 0 (Intercept): 2252.869278592447
Coefficient 1 (max_positive_polarity): 1205.19180317577

Dependent variable: avg_negative_polarity
R-squared: 0.003603052951085095
Coefficient 0 (Intercept): 2258.8852348515284
Coefficient 1 (avg_negative_polarity): -3496.854059710976

C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")

Dependent variable: min_negative_polarity
R-squared: 0.0017330748687242048
Coefficient 0 (Intercept): 2628.71950034944
Coefficient 1 (min_negative_polarity): -1050.0873043785075

Dependent variable: max_negative_polarity
R-squared: 0.0007739818092717954
Coefficient 0 (Intercept): 2964.064299733359
Coefficient 1 (max_negative_polarity): -2073.7589360703087

Dependent variable: title_subjectivity
R-squared: 0.0019803986610165136
Coefficient 0 (Intercept): 2920.647900607458
Coefficient 1 (title_subjectivity): 971.3835981890277

Dependent variable: title_sentiment_polarity
R-squared: 0.0012705721495491762
Coefficient 0 (Intercept): 3124.4450398637923
Coefficient 1 (title_sentiment_polarity): 951.708313995513

Dependent variable: abs_title_subjectivity
R-squared: 7.42457573199573e-08
Coefficient 0 (Intercept): 3196.747406745923
Coefficient 1 (abs_title_subjectivity): -10.190140616256855

Dependent variable: abs_title_sentiment_polarity
R-squared: 0.0026217984032116393
Coefficient 0 (Intercept): 2944.898700678077
Coefficient 1 (abs_title_sentiment_polarity): 1599.7811307291618

Dependent variable: data_channel
R-squared: 0.002264934887320047
Coefficient 0 (Intercept): 2414.731452360382
Coefficient 1 (data_channel): 178.84370814051215

Dependent variable: weekday_is
R-squared: 9.864917034907439e-05
Coefficient 0 (Intercept): 3058.039008945924
Coefficient 1 (weekday_is): 39.78692278047464

C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 0 (Intercept): {lin_model.params[0]}")
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2706907561.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Coefficient 1 ({i}): {lin_model.params[1]}")

In [17]:
LDA_03_model = smf.ols(formula=f'shares~ LDA_03', data=train_df).fit()
sm.qqplot(LDA_03_model.resid, line='s');

#### Multilinear Regression

In [18]:
# Turn list of predictors into string with plus signs that can be entered as model formula
def list_to_string(predictor_array):
    listToStr = '+'.join(map(str, predictor_array))
    print(listToStr)
    return listToStr

In [19]:
# Create a multilinear model that includes all predictors 
# Find coefficients that reduce the sum of least squares 
ml_model = smf.ols(formula='shares ~ {}'.format(list_to_string(predictors)), data=train_df).fit()
print(ml_model.summary())

n_tokens_title+n_tokens_content+n_non_stop_unique_tokens+num_hrefs+num_self_hrefs+num_imgs+num_videos+average_token_length+num_keywords+kw_min_min+kw_max_min+kw_min_max+kw_max_max+kw_avg_max+kw_min_avg+kw_max_avg+self_reference_min_shares+self_reference_max_shares+self_reference_avg_sharess+LDA_00+LDA_01+LDA_02+LDA_03+LDA_04+global_subjectivity+global_sentiment_polarity+global_rate_positive_words+global_rate_negative_words+rate_positive_words+rate_negative_words+avg_positive_polarity+min_positive_polarity+max_positive_polarity+avg_negative_polarity+min_negative_polarity+max_negative_polarity+title_subjectivity+title_sentiment_polarity+abs_title_subjectivity+abs_title_sentiment_polarity+data_channel+weekday_is
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                       0.038
Model:                            OLS   Adj. R-squared:                  0.037
Method:                 Least Squares   F-statistic:                     24.28
Date:                Fri, 25 Apr 2025   Prob (F-statistic):          1.82e-182
Time:                        22:29:47   Log-Likelihood:            -2.6431e+05
No. Observations:               25756   AIC:                         5.287e+05
Df Residuals:                   25713   BIC:                         5.291e+05
Df Model:                          42
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                    -8.402e+05   3.88e+05     -2.166      0.030    -1.6e+06   -7.99e+04
n_tokens_title                  62.4085     21.433      2.912      0.004      20.399     104.418
n_tokens_content                -0.1201      0.147     -0.817      0.414      -0.408       0.168
n_non_stop_unique_tokens      1299.5546    596.276      2.179      0.029     130.821    2468.289
num_hrefs                       39.0351      4.847      8.053      0.000      29.534      48.536
num_self_hrefs                 -63.0143     12.852     -4.903      0.000     -88.206     -37.823
num_imgs                        28.1012      6.667      4.215      0.000      15.033      41.169
num_videos                       2.5467     11.676      0.218      0.827     -20.338      25.432
average_token_length          -534.5721    170.166     -3.141      0.002    -868.107    -201.038
num_keywords                   121.6709     27.051      4.498      0.000      68.649     174.693
kw_min_min                       2.2418      1.196      1.875      0.061      -0.102       4.586
kw_max_min                      -0.0303      0.015     -2.025      0.043      -0.060      -0.001
kw_min_max                      -0.0018      0.001     -2.069      0.039      -0.004   -9.63e-05
kw_max_max                       0.0001      0.000      0.293      0.770      -0.001       0.001
kw_avg_max                       0.0014      0.001      2.432      0.015       0.000       0.002
kw_min_avg                       0.1378      0.044      3.116      0.002       0.051       0.224
kw_max_avg                       0.0750      0.010      7.395      0.000       0.055       0.095
self_reference_min_shares        0.0218      0.005      4.196      0.000       0.012       0.032
self_reference_max_shares        0.0075      0.003      2.612      0.009       0.002       0.013
self_reference_avg_sharess      -0.0120      0.007     -1.681      0.093      -0.026       0.002
LDA_00                        8.386e+05   3.87e+05      2.165      0.030    7.93e+04     1.6e+06
LDA_01                        8.381e+05   3.87e+05      2.164      0.031    7.88e+04     1.6e+06
LDA_02                        8.366e+05   3.87e+05      2.160      0.031    7.74e+04     1.6e+06
LDA_03                        8.389e+05   3.87e+05      2.166      0.030    7.96e+04     1.6e+06
LDA_04                        8.382e+05   3.87e+05      2.164      0.030    7.89e+04     1.6e+06
global_subjectivity           3487.7131    627.943      5.554      0.000    2256.910    4718.516
global_sentiment_polarity      603.7445   1246.180      0.484      0.628   -1838.839    3046.327
global_rate_positive_words   -3996.3570   5335.318     -0.749      0.454   -1.45e+04    6461.165
global_rate_negative_words   -3178.5984   1.02e+04     -0.313      0.755   -2.31e+04    1.68e+04
rate_positive_words            857.4127   4021.585      0.213      0.831   -7025.119    8739.945
rate_negative_words           1864.1969   4058.495      0.459      0.646   -6090.682    9819.076
avg_positive_polarity        -1030.9889   1012.679     -1.018      0.309   -3015.896     953.918
min_positive_polarity         -528.1581    826.258     -0.639      0.523   -2147.671    1091.355
max_positive_polarity          121.5099    314.750      0.386      0.699    -495.418     738.437
avg_negative_polarity        -1167.6483    925.681     -1.261      0.207   -2982.034     646.738
min_negative_polarity          -87.6383    335.671     -0.261      0.794    -745.572     570.295
max_negative_polarity          -25.7545    766.229     -0.034      0.973   -1527.606    1476.097
title_subjectivity             192.7572    205.897      0.936      0.349    -210.812     596.326
title_sentiment_polarity       695.0430    188.118      3.695      0.000     326.322    1063.764
abs_title_subjectivity         874.1610    273.027      3.202      0.001     339.013    1409.310
abs_title_sentiment_polarity   500.3675    296.817      1.686      0.092     -81.410    1082.145
data_channel                   203.7964     28.777      7.082      0.000     147.392     260.201
weekday_is                       1.7324     24.682      0.070      0.944     -46.646      50.111
==============================================================================
Omnibus:                    38057.511   Durbin-Watson:                   1.994
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         15780317.127
Skew:                           9.100   Prob(JB):                         0.00
Kurtosis:                     122.888   Cond. No.                     1.82e+10
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.82e+10. This might indicate that there are
strong multicollinearity or other numerical problems.

In [20]:
# Create a QQ plot for the residuals
sm.qqplot(ml_model.resid, line='s');

#### Enhancing Predictive Accuracy Through Regularization: Exploring Ridge and Lasso Regression

In [21]:
# Instantiate Ridge and Lasso regression models
# Alpha is a tuning parameter that determines strength of the regularization applied to the model
ridge_model = Ridge(alpha=1.0) 
lasso_model = Lasso(alpha=1.0)

# Fit the models to the training data
ridge_model.fit(X_train, y_train)
lasso_model.fit(X_train, y_train)

# Evaluate the models on the test data
ridge_r2 = ridge_model.score(X_test, y_test)
lasso_r2 = lasso_model.score(X_test, y_test)

print(f"R-squared for Ridge regression: {ridge_r2:.4f}")
print(f"R-squared for Lasso regression: {lasso_r2:.4f}")

R-squared for Ridge regression: 0.0281
R-squared for Lasso regression: 0.0284

#### Ridge and Lasso regression models using cross-validation for alpha selection

In [22]:
# Create Ridge and Lasso models with a range of alpha values
ridge_model = RidgeCV(alphas=[0.01, 0.1, 1.0, 5.0, 10.0, 20.0, 50.0])
lasso_model = LassoCV(alphas=[0.01, 0.1, 1.0, 5.0, 10.0, 20.0, 50.0], max_iter=10000)

# Fit the models to the training data
ridge_model.fit(X_train, y_train)
lasso_model.fit(X_train, y_train)

# Get the best alpha values from the models determined from cross-validation process
best_ridge_alpha = ridge_model.alpha_
best_lasso_alpha = lasso_model.alpha_

print(f"Best alpha for Ridge: {best_ridge_alpha:.4f}")
print(f"Best alpha for Lasso: {best_lasso_alpha:.4f}")

Best alpha for Ridge: 50.0000
Best alpha for Lasso: 10.0000

Now that I have the best alpha values, I will update the Ridge and Lasso models with this value and assess its performance on the test data. This iterative approach will allow me to strike the right balance between regularization and model fit, ultimately leading to a more accurate predictive model.

In [23]:
# Instantiate Ridge and Lasso regression models
ridge_model = Ridge(alpha=best_ridge_alpha) 
lasso_model = Lasso(alpha=best_lasso_alpha)

# Fit the models to the training data
ridge_model.fit(X_train, y_train)
lasso_model.fit(X_train, y_train)

# Evaluate the models on the test data
ridge_r2 = ridge_model.score(X_test, y_test)
lasso_r2 = lasso_model.score(X_test, y_test)

print(f"R-squared for Ridge regression: {ridge_r2:.4f}")
print(f"R-squared for Lasso regression: {lasso_r2:.4f}")

R-squared for Ridge regression: 0.0284
R-squared for Lasso regression: 0.0291

#### Multilinear Regression with Statistically Significant Predictors

In [24]:
significant_predictors = ['n_tokens_title', 'n_non_stop_unique_tokens', 'num_hrefs',
                          'num_self_hrefs', 'num_imgs', 'average_token_length', 'num_keywords',
                          'kw_max_min', 'kw_min_max', 'kw_avg_max', 'kw_min_avg', 'kw_max_avg',
                          'self_reference_min_shares', 'self_reference_max_shares', 'LDA_00',
                          'LDA_01', 'LDA_02', 'LDA_03', 'LDA_04', 'global_subjectivity', 
                          'title_sentiment_polarity', 'abs_title_subjectivity', 'data_channel'
                         ]

In [25]:
# Create a DataFrame with only significant predictors
X_train_significant = X_train[significant_predictors]
X_train_significant.insert(0, 'shares', y_train)  # Insert the target variable as the first column

# Initialize the list to keep track of selected predictors
selected_predictors = []

# Initialize the formula
formula = "shares ~ 1"  # Starting with intercept only

# Initialize variables to keep track of the best R-squared and predictor
best_r_squared = 0.0
best_predictor = None

# Perform forward stepwise regression
for _ in range(len(significant_predictors)):
    remaining_predictors = list(set(significant_predictors) - set(selected_predictors))
    r_squared_values = []
    
    for predictor in remaining_predictors:
        predictors = selected_predictors + [predictor]
        temp_formula = formula + " + " + " + ".join(predictors)
        
        temp_model = smf.ols(formula=temp_formula, data=X_train_significant).fit()
        r_squared = temp_model.rsquared_adj
        r_squared_values.append((predictor, r_squared))

    # Find the predictor with the highest increase in R-squared
    best_predictor, max_r_squared_increase = max(r_squared_values, key=lambda x: x[1])
    
    # Add the best predictor to the model
    selected_predictors.append(best_predictor)
    
    # Update the formula
    formula = formula + " + " + best_predictor

    # Update the best R-squared value
    best_r_squared = max_r_squared_increase
    
    # Print the current step's information
    print(f"Step {_+1}: Added predictor '{best_predictor}' (Adjusted R-squared: {best_r_squared:.4f})")

# Fit the final model
final_model = smf.ols(formula=formula, data=X_train_significant).fit()

print(final_model.summary())

Step 1: Added predictor 'LDA_03' (Adjusted R-squared: 0.0136)
Step 2: Added predictor 'kw_max_avg' (Adjusted R-squared: 0.0186)
Step 3: Added predictor 'global_subjectivity' (Adjusted R-squared: 0.0228)
Step 4: Added predictor 'self_reference_min_shares' (Adjusted R-squared: 0.0254)
Step 5: Added predictor 'num_hrefs' (Adjusted R-squared: 0.0281)
Step 6: Added predictor 'LDA_02' (Adjusted R-squared: 0.0294)
Step 7: Added predictor 'data_channel' (Adjusted R-squared: 0.0318)
Step 8: Added predictor 'title_sentiment_polarity' (Adjusted R-squared: 0.0323)
Step 9: Added predictor 'num_self_hrefs' (Adjusted R-squared: 0.0329)
Step 10: Added predictor 'num_imgs' (Adjusted R-squared: 0.0332)
Step 11: Added predictor 'n_tokens_title' (Adjusted R-squared: 0.0336)
Step 12: Added predictor 'self_reference_max_shares' (Adjusted R-squared: 0.0339)
Step 13: Added predictor 'average_token_length' (Adjusted R-squared: 0.0341)
Step 14: Added predictor 'num_keywords' (Adjusted R-squared: 0.0343)
Step 15: Added predictor 'kw_min_avg' (Adjusted R-squared: 0.0347)
Step 16: Added predictor 'LDA_00' (Adjusted R-squared: 0.0350)
Step 17: Added predictor 'abs_title_subjectivity' (Adjusted R-squared: 0.0352)
Step 18: Added predictor 'kw_max_min' (Adjusted R-squared: 0.0353)
Step 19: Added predictor 'kw_avg_max' (Adjusted R-squared: 0.0354)
Step 20: Added predictor 'kw_min_max' (Adjusted R-squared: 0.0354)
Step 21: Added predictor 'n_non_stop_unique_tokens' (Adjusted R-squared: 0.0354)
Step 22: Added predictor 'LDA_01' (Adjusted R-squared: 0.0354)
Step 23: Added predictor 'LDA_04' (Adjusted R-squared: 0.0356)
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                       0.036
Model:                            OLS   Adj. R-squared:                  0.036
Method:                 Least Squares   F-statistic:                     42.33
Date:                Fri, 25 Apr 2025   Prob (F-statistic):          2.86e-187
Time:                        22:30:07   Log-Likelihood:            -2.6433e+05
No. Observations:               25756   AIC:                         5.287e+05
Df Residuals:                   25732   BIC:                         5.289e+05
Df Model:                          23
Covariance Type:            nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
Intercept                  -8.55e+05    3.4e+05     -2.518      0.012   -1.52e+06    -1.9e+05
LDA_03                     8.552e+05   3.39e+05      2.522      0.012    1.91e+05    1.52e+06
kw_max_avg                    0.0754      0.010      7.453      0.000       0.056       0.095
global_subjectivity        3649.8095    533.881      6.836      0.000    2603.374    4696.245
self_reference_min_shares     0.0142      0.003      5.624      0.000       0.009       0.019
num_hrefs                    40.3462      4.638      8.698      0.000      31.255      49.438
LDA_02                     8.529e+05   3.39e+05      2.515      0.012    1.88e+05    1.52e+06
data_channel                213.9218     28.185      7.590      0.000     158.677     269.167
title_sentiment_polarity    726.4795    169.656      4.282      0.000     393.943    1059.016
num_self_hrefs              -64.0754     12.574     -5.096      0.000     -88.722     -39.429
num_imgs                     27.1041      6.443      4.207      0.000      14.476      39.732
n_tokens_title               64.4948     21.356      3.020      0.003      22.636     106.354
self_reference_max_shares     0.0033      0.001      2.825      0.005       0.001       0.006
average_token_length       -525.0197    165.126     -3.180      0.001    -848.676    -201.364
num_keywords                103.5292     26.049      3.974      0.000      52.471     154.587
kw_min_avg                    0.1377      0.044      3.120      0.002       0.051       0.224
LDA_00                     8.548e+05   3.39e+05      2.520      0.012     1.9e+05    1.52e+06
abs_title_subjectivity      566.7871    239.706      2.365      0.018      96.950    1036.624
kw_max_min                   -0.0305      0.015     -2.037      0.042      -0.060      -0.001
kw_avg_max                    0.0008      0.000      1.828      0.068   -5.55e-05       0.002
kw_min_max                   -0.0015      0.001     -1.778      0.075      -0.003       0.000
n_non_stop_unique_tokens   1322.4704    521.964      2.534      0.011     299.392    2345.549
LDA_01                     8.543e+05   3.39e+05      2.519      0.012     1.9e+05    1.52e+06
LDA_04                     8.542e+05   3.39e+05      2.519      0.012     1.9e+05    1.52e+06
==============================================================================
Omnibus:                    38108.204   Durbin-Watson:                   1.994
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         15898803.487
Skew:                           9.122   Prob(JB):                         0.00
Kurtosis:                     123.341   Cond. No.                     5.54e+09
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.54e+09. This might indicate that there are
strong multicollinearity or other numerical problems.

In [26]:
# Create a QQ plot for the residuals
sm.qqplot(final_model.resid, line='s');

In [27]:
significant_predictors2 = ['kw_max_avg', 'global_subjectivity', 'self_reference_min_shares',
                          'num_hrefs', 'data_channel', 'title_sentiment_polarity', 'num_self_hrefs',
                          'num_imgs', 'n_tokens_title', 'average_token_length', 'num_keywords',
                          'kw_min_avg'
                         ]

In [28]:
# Create a DataFrame with only significant predictors
X_train_significant = X_train[significant_predictors2]
X_train_significant.insert(0, 'shares', y_train)  # Insert the target variable as the first column

# Initialize the list to keep track of selected predictors
selected_predictors = []

# Initialize the formula
formula = "shares ~ 1"  # Starting with intercept only

# Initialize variables to keep track of the best R-squared and predictor
best_r_squared = 0.0
best_predictor = None

# Perform forward stepwise regression
for _ in range(len(significant_predictors2)):
    remaining_predictors = list(set(significant_predictors2) - set(selected_predictors))
    r_squared_values = []
    
    for predictor in remaining_predictors:
        predictors = selected_predictors + [predictor]
        temp_formula = formula + " + " + " + ".join(predictors)
        
        temp_model = smf.ols(formula=temp_formula, data=X_train_significant).fit()
        r_squared = temp_model.rsquared_adj
        r_squared_values.append((predictor, r_squared))

    # Find the predictor with the highest increase in R-squared
    best_predictor, max_r_squared_increase = max(r_squared_values, key=lambda x: x[1])
    
    # Add the best predictor to the model
    selected_predictors.append(best_predictor)
    
    # Update the formula
    formula = formula + " + " + best_predictor

    # Update the best R-squared value
    best_r_squared = max_r_squared_increase
    
    # Print the current step's information
    print(f"Step {_+1}: Added predictor '{best_predictor}' (Adjusted R-squared: {best_r_squared:.4f})")

# Fit the final model
final_model2 = smf.ols(formula=formula, data=X_train_significant).fit()

print(final_model2.summary())
print(formula)

Step 1: Added predictor 'global_subjectivity' (Adjusted R-squared: 0.0097)
Step 2: Added predictor 'kw_max_avg' (Adjusted R-squared: 0.0166)
Step 3: Added predictor 'num_hrefs' (Adjusted R-squared: 0.0202)
Step 4: Added predictor 'self_reference_min_shares' (Adjusted R-squared: 0.0231)
Step 5: Added predictor 'data_channel' (Adjusted R-squared: 0.0244)
Step 6: Added predictor 'num_imgs' (Adjusted R-squared: 0.0254)
Step 7: Added predictor 'average_token_length' (Adjusted R-squared: 0.0261)
Step 8: Added predictor 'num_self_hrefs' (Adjusted R-squared: 0.0269)
Step 9: Added predictor 'title_sentiment_polarity' (Adjusted R-squared: 0.0276)
Step 10: Added predictor 'kw_min_avg' (Adjusted R-squared: 0.0282)
Step 11: Added predictor 'num_keywords' (Adjusted R-squared: 0.0286)
Step 12: Added predictor 'n_tokens_title' (Adjusted R-squared: 0.0289)
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                       0.029
Model:                            OLS   Adj. R-squared:                  0.029
Method:                 Least Squares   F-statistic:                     64.78
Date:                Fri, 25 Apr 2025   Prob (F-statistic):          3.19e-156
Time:                        22:30:10   Log-Likelihood:            -2.6443e+05
No. Observations:               25756   AIC:                         5.289e+05
Df Residuals:                   25743   BIC:                         5.290e+05
Df Model:                          12
Covariance Type:            nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
Intercept                  1189.7174    874.695      1.360      0.174    -524.733    2904.168
global_subjectivity        5494.1464    511.260     10.746      0.000    4492.048    6496.245
kw_max_avg                    0.0819      0.008     10.492      0.000       0.067       0.097
num_hrefs                    39.5722      4.473      8.847      0.000      30.805      48.340
self_reference_min_shares     0.0187      0.002      8.301      0.000       0.014       0.023
data_channel                145.3847     23.579      6.166      0.000      99.168     191.601
num_imgs                     29.4859      5.667      5.203      0.000      18.377      40.594
average_token_length       -752.0465    161.445     -4.658      0.000   -1068.487    -435.606
num_self_hrefs              -60.6276     12.333     -4.916      0.000     -84.801     -36.455
title_sentiment_polarity    697.2811    164.570      4.237      0.000     374.715    1019.847
kw_min_avg                    0.2064      0.041      5.034      0.000       0.126       0.287
num_keywords                 90.1779     24.394      3.697      0.000      42.365     137.991
n_tokens_title               53.2970     20.763      2.567      0.010      12.599      93.995
==============================================================================
Omnibus:                    38128.757   Durbin-Watson:                   1.996
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         15843941.824
Skew:                           9.135   Prob(JB):                         0.00
Kurtosis:                     123.125   Cond. No.                     4.18e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.18e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
shares ~ 1 + global_subjectivity + kw_max_avg + num_hrefs + self_reference_min_shares + data_channel + num_imgs + average_token_length + num_self_hrefs + title_sentiment_polarity + kw_min_avg + num_keywords + n_tokens_title

In [29]:
# Create a QQ plot for the residuals
sm.qqplot(final_model2.resid, line='s');

#### Exploring Predictor Interactions with Random Forest

In [30]:
# Initialize and configure the model
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

# Fit the model on the training data
rf_model.fit(X_train, y_train)

# Predict on the test data
y_pred_rf = rf_model.predict(X_test)

# Calculate the R-squared value of the model
rf_r2 = rf_model.score(X_test, y_test)

# Get feature importances from the model
feature_importances = rf_model.feature_importances_

# Pair feature names with feature importances
feature_importance_pairs = list(zip(predictors, feature_importances))

# Sort feature importances in descending order
feature_importance_pairs.sort(key=lambda x: x[1], reverse=True)

print("Feature Importances:")
for feature, importance in feature_importance_pairs:
    print(f"{feature}: {importance:.4f}")

print(f"Random Forest R-squared: {rf_r2:.4f}")

Feature Importances:
num_self_hrefs: 0.0331
num_hrefs: 0.0325
num_keywords: 0.0310
self_reference_min_shares: 0.0305
kw_max_avg: 0.0291
global_subjectivity: 0.0253
num_imgs: 0.0184
data_channel: 0.0164
average_token_length: 0.0137
n_tokens_title: 0.0121
title_sentiment_polarity: 0.0098
kw_min_avg: 0.0033
Random Forest R-squared: -0.0643

To further explore the potential interactions among predictors identified by the Random Forest analysis, I conducted a multilinear regression analysis. The goal was to assess how the inclusion of interaction terms could enhance the model's explanatory power.

In [31]:
selected_features = [feature for feature, importance in feature_importance_pairs[:12]]

In [32]:
# Create a new DataFrame with only the selected features for training
train_df_selected = train_df[selected_features + ['shares']]

In [33]:
# Create interaction terms
interaction_terms = []
for predictor1 in selected_features:
    for predictor2 in selected_features:
        if predictor1 != predictor2:
            interaction_name = f"{predictor1}_{predictor2}"
            train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
            interaction_terms.append(interaction_name)

# Prepare data with interaction terms
data_with_interactions = pd.concat([train_df_selected, train_df_selected[interaction_terms]], axis=1).copy()

# Run multilinear regression with interaction terms
results = []
for interaction in interaction_terms:
    formula = f'shares ~ {" + ".join(selected_features + [interaction])}'
    ml_model = smf.ols(formula=formula, data=data_with_interactions).fit()
    results.append((interaction, ml_model.rsquared_adj))

results.sort(key=lambda x: x[1], reverse=True)
for interaction_name, adj_r2 in results:
    print(f"Interaction: {interaction_name}, Adjusted R-squared: {adj_r2:.4f}")

C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]
C:\Users\mktgs\AppData\Local\Temp\ipykernel_12524\2897819729.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_df_selected[interaction_name] = train_df_selected[predictor1] * train_df_selected[predictor2]

Interaction: self_reference_min_shares_global_subjectivity, Adjusted R-squared: 0.0308
Interaction: global_subjectivity_self_reference_min_shares, Adjusted R-squared: 0.0308
Interaction: self_reference_min_shares_num_imgs, Adjusted R-squared: 0.0306
Interaction: num_imgs_self_reference_min_shares, Adjusted R-squared: 0.0306
Interaction: kw_max_avg_num_imgs, Adjusted R-squared: 0.0301
Interaction: num_imgs_kw_max_avg, Adjusted R-squared: 0.0301
Interaction: global_subjectivity_data_channel, Adjusted R-squared: 0.0298
Interaction: data_channel_global_subjectivity, Adjusted R-squared: 0.0298
Interaction: num_keywords_kw_max_avg, Adjusted R-squared: 0.0297
Interaction: kw_max_avg_num_keywords, Adjusted R-squared: 0.0297
Interaction: num_imgs_average_token_length, Adjusted R-squared: 0.0297
Interaction: average_token_length_num_imgs, Adjusted R-squared: 0.0297
Interaction: num_self_hrefs_num_imgs, Adjusted R-squared: 0.0297
Interaction: num_imgs_num_self_hrefs, Adjusted R-squared: 0.0297
Interaction: num_self_hrefs_n_tokens_title, Adjusted R-squared: 0.0295
Interaction: n_tokens_title_num_self_hrefs, Adjusted R-squared: 0.0295
Interaction: num_self_hrefs_average_token_length, Adjusted R-squared: 0.0295
Interaction: average_token_length_num_self_hrefs, Adjusted R-squared: 0.0295
Interaction: num_hrefs_n_tokens_title, Adjusted R-squared: 0.0295
Interaction: n_tokens_title_num_hrefs, Adjusted R-squared: 0.0295
Interaction: kw_max_avg_data_channel, Adjusted R-squared: 0.0292
Interaction: data_channel_kw_max_avg, Adjusted R-squared: 0.0292
Interaction: global_subjectivity_title_sentiment_polarity, Adjusted R-squared: 0.0292
Interaction: title_sentiment_polarity_global_subjectivity, Adjusted R-squared: 0.0292
Interaction: num_hrefs_num_imgs, Adjusted R-squared: 0.0292
Interaction: num_imgs_num_hrefs, Adjusted R-squared: 0.0292
Interaction: data_channel_title_sentiment_polarity, Adjusted R-squared: 0.0291
Interaction: title_sentiment_polarity_data_channel, Adjusted R-squared: 0.0291
Interaction: num_self_hrefs_global_subjectivity, Adjusted R-squared: 0.0291
Interaction: global_subjectivity_num_self_hrefs, Adjusted R-squared: 0.0291
Interaction: kw_max_avg_n_tokens_title, Adjusted R-squared: 0.0291
Interaction: n_tokens_title_kw_max_avg, Adjusted R-squared: 0.0291
Interaction: self_reference_min_shares_title_sentiment_polarity, Adjusted R-squared: 0.0290
Interaction: title_sentiment_polarity_self_reference_min_shares, Adjusted R-squared: 0.0290
Interaction: average_token_length_n_tokens_title, Adjusted R-squared: 0.0290
Interaction: n_tokens_title_average_token_length, Adjusted R-squared: 0.0290
Interaction: num_keywords_num_imgs, Adjusted R-squared: 0.0290
Interaction: num_imgs_num_keywords, Adjusted R-squared: 0.0290
Interaction: average_token_length_title_sentiment_polarity, Adjusted R-squared: 0.0290
Interaction: title_sentiment_polarity_average_token_length, Adjusted R-squared: 0.0290
Interaction: num_keywords_data_channel, Adjusted R-squared: 0.0290
Interaction: data_channel_num_keywords, Adjusted R-squared: 0.0290
Interaction: num_imgs_n_tokens_title, Adjusted R-squared: 0.0290
Interaction: n_tokens_title_num_imgs, Adjusted R-squared: 0.0290
Interaction: num_keywords_average_token_length, Adjusted R-squared: 0.0290
Interaction: average_token_length_num_keywords, Adjusted R-squared: 0.0290
Interaction: num_self_hrefs_num_hrefs, Adjusted R-squared: 0.0290
Interaction: num_hrefs_num_self_hrefs, Adjusted R-squared: 0.0290
Interaction: kw_max_avg_title_sentiment_polarity, Adjusted R-squared: 0.0290
Interaction: title_sentiment_polarity_kw_max_avg, Adjusted R-squared: 0.0290
Interaction: num_self_hrefs_title_sentiment_polarity, Adjusted R-squared: 0.0290
Interaction: title_sentiment_polarity_num_self_hrefs, Adjusted R-squared: 0.0290
Interaction: num_keywords_self_reference_min_shares, Adjusted R-squared: 0.0289
Interaction: self_reference_min_shares_num_keywords, Adjusted R-squared: 0.0289
Interaction: num_hrefs_self_reference_min_shares, Adjusted R-squared: 0.0289
Interaction: self_reference_min_shares_num_hrefs, Adjusted R-squared: 0.0289
Interaction: num_hrefs_num_keywords, Adjusted R-squared: 0.0289
Interaction: num_keywords_num_hrefs, Adjusted R-squared: 0.0289
Interaction: num_keywords_kw_min_avg, Adjusted R-squared: 0.0289
Interaction: kw_min_avg_num_keywords, Adjusted R-squared: 0.0289
Interaction: num_hrefs_data_channel, Adjusted R-squared: 0.0289
Interaction: data_channel_num_hrefs, Adjusted R-squared: 0.0289
Interaction: num_imgs_data_channel, Adjusted R-squared: 0.0289
Interaction: data_channel_num_imgs, Adjusted R-squared: 0.0289
Interaction: num_imgs_kw_min_avg, Adjusted R-squared: 0.0289
Interaction: kw_min_avg_num_imgs, Adjusted R-squared: 0.0289
Interaction: global_subjectivity_n_tokens_title, Adjusted R-squared: 0.0289
Interaction: n_tokens_title_global_subjectivity, Adjusted R-squared: 0.0289
Interaction: data_channel_kw_min_avg, Adjusted R-squared: 0.0289
Interaction: kw_min_avg_data_channel, Adjusted R-squared: 0.0289
Interaction: global_subjectivity_kw_min_avg, Adjusted R-squared: 0.0289
Interaction: kw_min_avg_global_subjectivity, Adjusted R-squared: 0.0289
Interaction: num_self_hrefs_num_keywords, Adjusted R-squared: 0.0289
Interaction: num_keywords_num_self_hrefs, Adjusted R-squared: 0.0289
Interaction: num_self_hrefs_data_channel, Adjusted R-squared: 0.0289
Interaction: data_channel_num_self_hrefs, Adjusted R-squared: 0.0289
Interaction: kw_max_avg_kw_min_avg, Adjusted R-squared: 0.0289
Interaction: kw_min_avg_kw_max_avg, Adjusted R-squared: 0.0289
Interaction: num_keywords_n_tokens_title, Adjusted R-squared: 0.0289
Interaction: n_tokens_title_num_keywords, Adjusted R-squared: 0.0289
Interaction: self_reference_min_shares_kw_max_avg, Adjusted R-squared: 0.0289
Interaction: kw_max_avg_self_reference_min_shares, Adjusted R-squared: 0.0289
Interaction: n_tokens_title_title_sentiment_polarity, Adjusted R-squared: 0.0289
Interaction: title_sentiment_polarity_n_tokens_title, Adjusted R-squared: 0.0289
Interaction: num_self_hrefs_self_reference_min_shares, Adjusted R-squared: 0.0289
Interaction: self_reference_min_shares_num_self_hrefs, Adjusted R-squared: 0.0289
Interaction: global_subjectivity_average_token_length, Adjusted R-squared: 0.0289
Interaction: average_token_length_global_subjectivity, Adjusted R-squared: 0.0289
Interaction: data_channel_average_token_length, Adjusted R-squared: 0.0289
Interaction: average_token_length_data_channel, Adjusted R-squared: 0.0289
Interaction: data_channel_n_tokens_title, Adjusted R-squared: 0.0289
Interaction: n_tokens_title_data_channel, Adjusted R-squared: 0.0289
Interaction: num_imgs_title_sentiment_polarity, Adjusted R-squared: 0.0288
Interaction: title_sentiment_polarity_num_imgs, Adjusted R-squared: 0.0288
Interaction: average_token_length_kw_min_avg, Adjusted R-squared: 0.0288
Interaction: kw_min_avg_average_token_length, Adjusted R-squared: 0.0288
Interaction: kw_max_avg_average_token_length, Adjusted R-squared: 0.0288
Interaction: average_token_length_kw_max_avg, Adjusted R-squared: 0.0288
Interaction: self_reference_min_shares_n_tokens_title, Adjusted R-squared: 0.0288
Interaction: n_tokens_title_self_reference_min_shares, Adjusted R-squared: 0.0288
Interaction: self_reference_min_shares_average_token_length, Adjusted R-squared: 0.0288
Interaction: average_token_length_self_reference_min_shares, Adjusted R-squared: 0.0288
Interaction: self_reference_min_shares_data_channel, Adjusted R-squared: 0.0288
Interaction: data_channel_self_reference_min_shares, Adjusted R-squared: 0.0288
Interaction: num_hrefs_kw_max_avg, Adjusted R-squared: 0.0288
Interaction: kw_max_avg_num_hrefs, Adjusted R-squared: 0.0288
Interaction: global_subjectivity_num_imgs, Adjusted R-squared: 0.0288
Interaction: num_imgs_global_subjectivity, Adjusted R-squared: 0.0288
Interaction: num_keywords_global_subjectivity, Adjusted R-squared: 0.0288
Interaction: global_subjectivity_num_keywords, Adjusted R-squared: 0.0288
Interaction: num_keywords_title_sentiment_polarity, Adjusted R-squared: 0.0288
Interaction: title_sentiment_polarity_num_keywords, Adjusted R-squared: 0.0288
Interaction: num_hrefs_average_token_length, Adjusted R-squared: 0.0288
Interaction: average_token_length_num_hrefs, Adjusted R-squared: 0.0288
Interaction: num_self_hrefs_kw_min_avg, Adjusted R-squared: 0.0288
Interaction: kw_min_avg_num_self_hrefs, Adjusted R-squared: 0.0288
Interaction: num_hrefs_kw_min_avg, Adjusted R-squared: 0.0288
Interaction: kw_min_avg_num_hrefs, Adjusted R-squared: 0.0288
Interaction: self_reference_min_shares_kw_min_avg, Adjusted R-squared: 0.0288
Interaction: kw_min_avg_self_reference_min_shares, Adjusted R-squared: 0.0288
Interaction: num_hrefs_global_subjectivity, Adjusted R-squared: 0.0288
Interaction: global_subjectivity_num_hrefs, Adjusted R-squared: 0.0288
Interaction: n_tokens_title_kw_min_avg, Adjusted R-squared: 0.0288
Interaction: kw_min_avg_n_tokens_title, Adjusted R-squared: 0.0288
Interaction: kw_max_avg_global_subjectivity, Adjusted R-squared: 0.0288
Interaction: global_subjectivity_kw_max_avg, Adjusted R-squared: 0.0288
Interaction: num_hrefs_title_sentiment_polarity, Adjusted R-squared: 0.0288
Interaction: title_sentiment_polarity_num_hrefs, Adjusted R-squared: 0.0288
Interaction: num_self_hrefs_kw_max_avg, Adjusted R-squared: 0.0288
Interaction: kw_max_avg_num_self_hrefs, Adjusted R-squared: 0.0288
Interaction: title_sentiment_polarity_kw_min_avg, Adjusted R-squared: 0.0288
Interaction: kw_min_avg_title_sentiment_polarity, Adjusted R-squared: 0.0288

In [34]:
# Top 3 interaction terms
top_interactions = [
    "self_reference_min_shares_global_subjectivity",
    "kw_max_avg_num_imgs",
    "self_reference_min_shares_num_imgs"
]

# Prepare data with top interaction terms
data_with_top_interactions = pd.concat([train_df_selected, train_df_selected[top_interactions]], axis=1)

# Run multilinear regression with top interaction terms
for interaction in top_interactions:
    formula = f'shares ~ {" + ".join(selected_features + [interaction])}'
    ml_model = smf.ols(formula=formula, data=data_with_top_interactions).fit()
    print(f"Interaction: {interaction}")
    print(ml_model.summary())
    # Create a QQ plot for the residuals
    sm.qqplot(ml_model.resid, line='s')

Interaction: self_reference_min_shares_global_subjectivity
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                       0.031
Model:                            OLS   Adj. R-squared:                  0.031
Method:                 Least Squares   F-statistic:                     63.96
Date:                Fri, 25 Apr 2025   Prob (F-statistic):          1.46e-166
Time:                        22:33:55   Log-Likelihood:            -2.6440e+05
No. Observations:               25756   AIC:                         5.288e+05
Df Residuals:                   25742   BIC:                         5.289e+05
Df Model:                          13
Covariance Type:            nonrobust
====================================================================================================================
                                                       coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------------
Intercept                                         1791.7596    877.754      2.041      0.041      71.313    3512.206
num_self_hrefs                                     -60.5472     12.320     -4.914      0.000     -84.696     -36.398
num_hrefs                                           39.5657      4.469      8.854      0.000      30.807      48.324
num_keywords                                        91.5751     24.370      3.758      0.000      43.808     139.342
self_reference_min_shares                           -0.0772      0.013     -5.752      0.000      -0.103      -0.051
kw_max_avg                                           0.0815      0.008     10.453      0.000       0.066       0.097
global_subjectivity                               4578.3279    526.128      8.702      0.000    3547.088    5609.568
num_imgs                                            29.0827      5.662      5.136      0.000      17.985      40.181
data_channel                                       141.9827     23.560      6.026      0.000      95.803     188.162
average_token_length                              -784.8161    161.347     -4.864      0.000   -1101.064    -468.568
n_tokens_title                                      51.7184     20.744      2.493      0.013      11.059      92.378
title_sentiment_polarity                           696.5217    164.405      4.237      0.000     374.279    1018.765
kw_min_avg                                           0.2073      0.041      5.061      0.000       0.127       0.288
self_reference_min_shares_global_subjectivity[0]     0.0997      0.014      7.252      0.000       0.073       0.127
self_reference_min_shares_global_subjectivity[1]     0.0997      0.014      7.252      0.000       0.073       0.127
==============================================================================
Omnibus:                    38031.287   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         15651852.115
Skew:                           9.091   Prob(JB):                         0.00
Kurtosis:                     122.391   Cond. No.                     5.07e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.76e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
Interaction: kw_max_avg_num_imgs
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                       0.031
Model:                            OLS   Adj. R-squared:                  0.030
Method:                 Least Squares   F-statistic:                     62.40
Date:                Fri, 25 Apr 2025   Prob (F-statistic):          2.44e-162
Time:                        22:33:55   Log-Likelihood:            -2.6441e+05
No. Observations:               25756   AIC:                         5.289e+05
Df Residuals:                   25742   BIC:                         5.290e+05
Df Model:                          13
Covariance Type:            nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
Intercept                  1625.2494    877.449      1.852      0.064     -94.601    3345.100
num_self_hrefs              -54.3202     12.374     -4.390      0.000     -78.574     -30.066
num_hrefs                    38.5828      4.474      8.625      0.000      29.814      47.351
num_keywords                 88.6563     24.380      3.636      0.000      40.870     136.443
self_reference_min_shares     0.0185      0.002      8.215      0.000       0.014       0.023
kw_max_avg                    0.0548      0.009      5.999      0.000       0.037       0.073
global_subjectivity        5423.6140    511.092     10.612      0.000    4421.845    6425.383
num_imgs                     -7.6656      8.607     -0.891      0.373     -24.536       9.205
data_channel                137.2753     23.607      5.815      0.000      91.004     183.547
average_token_length       -796.8166    161.534     -4.933      0.000   -1113.432    -480.201
n_tokens_title               53.1908     20.751      2.563      0.010      12.518      93.863
title_sentiment_polarity    693.2208    164.469      4.215      0.000     370.852    1015.590
kw_min_avg                    0.1984      0.041      4.837      0.000       0.118       0.279
kw_max_avg_num_imgs[0]        0.0030      0.001      5.732      0.000       0.002       0.004
kw_max_avg_num_imgs[1]        0.0030      0.001      5.732      0.000       0.002       0.004
==============================================================================
Omnibus:                    38116.752   Durbin-Watson:                   1.996
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         15842044.232
Skew:                           9.128   Prob(JB):                         0.00
Kurtosis:                     123.119   Cond. No.                     7.30e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.87e-18. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
Interaction: self_reference_min_shares_num_imgs
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                       0.031
Model:                            OLS   Adj. R-squared:                  0.031
Method:                 Least Squares   F-statistic:                     63.51
Date:                Fri, 25 Apr 2025   Prob (F-statistic):          2.41e-165
Time:                        22:33:55   Log-Likelihood:            -2.6440e+05
No. Observations:               25756   AIC:                         5.288e+05
Df Residuals:                   25742   BIC:                         5.290e+05
Df Model:                          13
Covariance Type:            nonrobust
=========================================================================================================
                                            coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
Intercept                              1432.2379    874.633      1.638      0.102    -282.091    3146.567
num_self_hrefs                          -54.2368     12.357     -4.389      0.000     -78.457     -30.016
num_hrefs                                39.0122      4.470      8.728      0.000      30.251      47.773
num_keywords                             86.7390     24.377      3.558      0.000      38.958     134.520
self_reference_min_shares                 0.0102      0.003      3.974      0.000       0.005       0.015
kw_max_avg                                0.0796      0.008     10.197      0.000       0.064       0.095
global_subjectivity                    5382.6372    511.064     10.532      0.000    4380.923    6384.352
num_imgs                                 18.7659      5.875      3.194      0.001       7.251      30.281
data_channel                            140.0542     23.571      5.942      0.000      93.853     186.255
average_token_length                   -778.5269    161.347     -4.825      0.000   -1094.777    -462.277
n_tokens_title                           54.5683     20.746      2.630      0.009      13.905      95.231
title_sentiment_polarity                686.9329    164.430      4.178      0.000     364.641    1009.225
kw_min_avg                                0.1977      0.041      4.822      0.000       0.117       0.278
self_reference_min_shares_num_imgs[0]     0.0015      0.000      6.849      0.000       0.001       0.002
self_reference_min_shares_num_imgs[1]     0.0015      0.000      6.849      0.000       0.001       0.002
==============================================================================
Omnibus:                    38071.599   Durbin-Watson:                   1.996
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         15734661.378
Skew:                           9.109   Prob(JB):                         0.00
Kurtosis:                     122.708   Cond. No.                     4.60e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.65e-17. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

#### Summary of Results & Analysis: Exploring Predictor Interactions with Random Forest

I incorporated interaction terms into the model based on the top-performing interactions from the Random Forest analysis. The selected interaction terms were:

* self_reference_min_shares_global_subjectivity
* kw_max_avg_num_imgs
* self_reference_min_shares_num_imgs

These interactions were chosen due to their relatively higher adjusted R-squared values and their potential to reveal intricate relationships between predictors.

The multilinear regression models with interaction terms exhibited limited improvement in explaining the variance in the target variable, "shares." The adjusted R-squared values for these models was 0.031. While statistically significant, these values indicate that only about 3.1% of the variation in the target variable could be explained by the included predictors and their interactions.

This modest increase in adjusted R-squared as compared to the multilinear model with statistically significant predictors suggests that while these interaction terms contribute to the model's predictive capacity, they do not strongly enhance its overall performance. It's important to note that the inclusion of interaction terms can introduce multicollinearity and increase model complexity, potentially leading to overfitting. Thus far, the model with the highest R-squared is the multilinear model with all predictors.

#### Multicollinearity Detection: VIF

In [35]:
# Get variables for which to compute VIF and add intercept term
# set all values in intercept term to 1
x_df_train['Intercept'] = 1
x_df_train.head()

,n_tokens_title,n_tokens_content,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,num_keywords,kw_min_min,...,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,data_channel,weekday_is,Intercept
35308,12.0,294.0,0.820359,7.0,5.0,2.0,1.0,4.625850,7.0,-1.0,...,-0.332143,-0.400000,-0.1250,0.00000,0.000000,0.50000,0.000000,2,3,1
2595,11.0,284.0,0.762500,1.0,0.0,1.0,1.0,4.690141,5.0,217.0,...,-0.194444,-0.300000,-0.1000,0.60000,0.200000,0.10000,0.200000,3,4,1
6100,10.0,254.0,0.745455,7.0,5.0,1.0,0.0,4.748031,6.0,4.0,...,-0.133333,-0.166667,-0.1000,0.00000,0.000000,0.50000,0.000000,3,2,1
11827,9.0,292.0,0.750000,6.0,5.0,0.0,17.0,4.602740,5.0,4.0,...,-0.475000,-0.700000,-0.2000,0.49513,0.211039,0.00487,0.211039,4,4,1
12758,11.0,306.0,0.741573,15.0,2.0,15.0,0.0,4.205882,10.0,4.0,...,-0.473438,-1.000000,-0.1875,0.00000,0.000000,0.50000,0.000000,7,3,1

In [36]:
# Compute and view VIF
vif = pd.DataFrame()
# using variance inflation factor from Statsmodel
vif['variables'] = x_df_train.columns
vif["VIF"] = [variance_inflation_factor(x_df_train.values, i) for i in range(x_df_train.shape[1])]
print(vif)

                       variables           VIF
0                 n_tokens_title  1.086528e+00
1               n_tokens_content  2.508867e+00
2       n_non_stop_unique_tokens  3.120861e+03
3                      num_hrefs  1.624994e+00
4                 num_self_hrefs  1.346270e+00
5                       num_imgs  1.620733e+00
6                     num_videos  1.238578e+00
7           average_token_length  1.258831e+00
8                   num_keywords  1.434711e+00
9                     kw_min_min  3.754937e+00
10                    kw_max_min  1.621238e+00
11                    kw_min_max  1.356872e+00
12                    kw_max_max  4.452995e+00
13                    kw_avg_max  2.917122e+00
14                    kw_min_avg  1.327269e+00
15                    kw_max_avg  1.794655e+00
16     self_reference_min_shares  5.388084e+00
17     self_reference_max_shares  8.086168e+00
18    self_reference_avg_sharess  1.660755e+01
19                        LDA_00  5.743000e+06
20                        LDA_01  3.864430e+06
21                        LDA_02  6.422232e+06
22                        LDA_03  6.665449e+06
23                        LDA_04  6.818902e+06
24           global_subjectivity  1.628999e+00
25     global_sentiment_polarity  7.620645e+00
26    global_rate_positive_words  3.959683e+00
27    global_rate_negative_words  6.166344e+00
28           rate_positive_words  1.938518e+02
29           rate_negative_words  1.968686e+02
30         avg_positive_polarity  4.019695e+00
31         min_positive_polarity  1.837747e+00
32         max_positive_polarity  2.384099e+00
33         avg_negative_polarity  6.749696e+00
34         min_negative_polarity  4.734122e+00
35         max_negative_polarity  2.824733e+00
36            title_subjectivity  2.378571e+00
37      title_sentiment_polarity  1.327079e+00
38        abs_title_subjectivity  1.424850e+00
39  abs_title_sentiment_polarity  2.412687e+00
40                  data_channel  1.567655e+00
41                    weekday_is  1.014917e+00
42                     Intercept  8.064023e+07

In [37]:
# drop predictors with VIF greater than 5
columns_to_drop = ['self_reference_min_shares', 'self_reference_max_shares',
                'LDA_00', 'LDA_02', 'LDA_03', 'LDA_04', 'global_sentiment_polarity',
                'global_rate_negative_words', 'avg_negative_polarity']

x_df_train = x_df_train.drop(columns_to_drop, axis=1)
x_df_train.head()

,n_tokens_title,n_tokens_content,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,num_keywords,kw_min_min,...,max_positive_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,data_channel,weekday_is,Intercept
35308,12.0,294.0,0.820359,7.0,5.0,2.0,1.0,4.625850,7.0,-1.0,...,1.0,-0.400000,-0.1250,0.00000,0.000000,0.50000,0.000000,2,3,1
2595,11.0,284.0,0.762500,1.0,0.0,1.0,1.0,4.690141,5.0,217.0,...,0.8,-0.300000,-0.1000,0.60000,0.200000,0.10000,0.200000,3,4,1
6100,10.0,254.0,0.745455,7.0,5.0,1.0,0.0,4.748031,6.0,4.0,...,0.7,-0.166667,-0.1000,0.00000,0.000000,0.50000,0.000000,3,2,1
11827,9.0,292.0,0.750000,6.0,5.0,0.0,17.0,4.602740,5.0,4.0,...,1.0,-0.700000,-0.2000,0.49513,0.211039,0.00487,0.211039,4,4,1
12758,11.0,306.0,0.741573,15.0,2.0,15.0,0.0,4.205882,10.0,4.0,...,1.0,-1.000000,-0.1875,0.00000,0.000000,0.50000,0.000000,7,3,1

In [38]:
# Compute and view VIF to ensure all interactions are below 5
vif2 = pd.DataFrame()
# using variance inflation factor from Statsmodel
vif2['variables'] = x_df_train.columns
vif2["VIF"] = [variance_inflation_factor(x_df_train.values, i) for i in range(x_df_train.shape[1])]
print(vif2)

                       variables          VIF
0                 n_tokens_title     1.073025
1               n_tokens_content     1.999601
2       n_non_stop_unique_tokens     1.335710
3                      num_hrefs     1.574064
4                 num_self_hrefs     1.261591
5                       num_imgs     1.321363
6                     num_videos     1.126530
7           average_token_length     1.177110
8                   num_keywords     1.393974
9                     kw_min_min     3.745997
10                    kw_max_min     1.610859
11                    kw_min_max     1.341448
12                    kw_max_max     4.346782
13                    kw_avg_max     2.529692
14                    kw_min_avg     1.314823
15                    kw_max_avg     1.746513
16    self_reference_avg_sharess     1.037253
17                        LDA_01     1.174310
18           global_subjectivity     1.462172
19    global_rate_positive_words     1.867828
20           rate_positive_words   193.340158
21           rate_negative_words   193.069220
22         avg_positive_polarity     2.548287
23         min_positive_polarity     1.773965
24         max_positive_polarity     2.364588
25         min_negative_polarity     1.825794
26         max_negative_polarity     1.184199
27            title_subjectivity     2.372375
28      title_sentiment_polarity     1.297834
29        abs_title_subjectivity     1.419227
30  abs_title_sentiment_polarity     2.401057
31                  data_channel     1.209873
32                    weekday_is     1.013317
33                     Intercept  9020.129130

The rate_positive_words and rate_negative_words have a threshold over 5 and will be dropped from the dataset.

In [39]:
# drop predictors with VIF greater than 5
columns_to_drop = ['rate_positive_words', 'rate_negative_words']

x_df_train = x_df_train.drop(columns_to_drop, axis=1)
x_df_train.head()

,n_tokens_title,n_tokens_content,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,num_keywords,kw_min_min,...,max_positive_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,data_channel,weekday_is,Intercept
35308,12.0,294.0,0.820359,7.0,5.0,2.0,1.0,4.625850,7.0,-1.0,...,1.0,-0.400000,-0.1250,0.00000,0.000000,0.50000,0.000000,2,3,1
2595,11.0,284.0,0.762500,1.0,0.0,1.0,1.0,4.690141,5.0,217.0,...,0.8,-0.300000,-0.1000,0.60000,0.200000,0.10000,0.200000,3,4,1
6100,10.0,254.0,0.745455,7.0,5.0,1.0,0.0,4.748031,6.0,4.0,...,0.7,-0.166667,-0.1000,0.00000,0.000000,0.50000,0.000000,3,2,1
11827,9.0,292.0,0.750000,6.0,5.0,0.0,17.0,4.602740,5.0,4.0,...,1.0,-0.700000,-0.2000,0.49513,0.211039,0.00487,0.211039,4,4,1
12758,11.0,306.0,0.741573,15.0,2.0,15.0,0.0,4.205882,10.0,4.0,...,1.0,-1.000000,-0.1875,0.00000,0.000000,0.50000,0.000000,7,3,1

In [40]:
# Compute and view VIF to ensure all interactions are below 5
vif3 = pd.DataFrame()
# using variance inflation factor from Statsmodel
vif3['variables'] = x_df_train.columns
vif3["VIF"] = [variance_inflation_factor(x_df_train.values, i) for i in range(x_df_train.shape[1])]
print(vif3)

                       variables         VIF
0                 n_tokens_title    1.072125
1               n_tokens_content    1.979820
2       n_non_stop_unique_tokens    1.003292
3                      num_hrefs    1.569576
4                 num_self_hrefs    1.260905
5                       num_imgs    1.320565
6                     num_videos    1.117591
7           average_token_length    1.176463
8                   num_keywords    1.393754
9                     kw_min_min    3.745862
10                    kw_max_min    1.610717
11                    kw_min_max    1.341134
12                    kw_max_max    4.346525
13                    kw_avg_max    2.529553
14                    kw_min_avg    1.313713
15                    kw_max_avg    1.746246
16    self_reference_avg_sharess    1.037203
17                        LDA_01    1.171346
18           global_subjectivity    1.455265
19    global_rate_positive_words    1.450374
20         avg_positive_polarity    2.546236
21         min_positive_polarity    1.766104
22         max_positive_polarity    2.347649
23         min_negative_polarity    1.405993
24         max_negative_polarity    1.131885
25            title_subjectivity    2.369599
26      title_sentiment_polarity    1.277577
27        abs_title_subjectivity    1.416466
28  abs_title_sentiment_polarity    2.400395
29                  data_channel    1.204768
30                    weekday_is    1.012599
31                     Intercept  515.298531

Now that VIF for all intereactions is below 5. I can rerun the multilinear model.

In [41]:
predictors_wo_multicol = [
    'n_tokens_title', 'n_tokens_content', 'n_non_stop_unique_tokens',
    'num_hrefs', 'num_self_hrefs', 'num_imgs',
    'num_videos', 'average_token_length', 'num_keywords',
    'kw_min_min', 'kw_max_min', 'kw_min_max',
    'kw_max_max', 'kw_avg_max', 'kw_min_avg',
    'kw_max_avg', 'self_reference_avg_sharess', 'LDA_01',
    'global_subjectivity', 'global_rate_positive_words', 'avg_positive_polarity',
    'min_positive_polarity', 'max_positive_polarity', 'min_negative_polarity',
    'max_negative_polarity', 'title_subjectivity', 'title_sentiment_polarity',
    'abs_title_subjectivity', 'abs_title_sentiment_polarity', 'data_channel',
    'weekday_is'
]

In [42]:
no_multicol_model = smf.ols(formula='shares ~ {}'.format(list_to_string(predictors_wo_multicol)), data=train_df).fit()
no_multicol_model.summary()

n_tokens_title+n_tokens_content+n_non_stop_unique_tokens+num_hrefs+num_self_hrefs+num_imgs+num_videos+average_token_length+num_keywords+kw_min_min+kw_max_min+kw_min_max+kw_max_max+kw_avg_max+kw_min_avg+kw_max_avg+self_reference_avg_sharess+LDA_01+global_subjectivity+global_rate_positive_words+avg_positive_polarity+min_positive_polarity+max_positive_polarity+min_negative_polarity+max_negative_polarity+title_subjectivity+title_sentiment_polarity+abs_title_subjectivity+abs_title_sentiment_polarity+data_channel+weekday_is

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                       0.033
Model:                            OLS   Adj. R-squared:                  0.032
Method:                 Least Squares   F-statistic:                     28.55
Date:                Fri, 25 Apr 2025   Prob (F-statistic):          5.28e-163
Time:                        22:34:04   Log-Likelihood:            -2.6438e+05
No. Observations:               25756   AIC:                         5.288e+05
Df Residuals:                   25724   BIC:                         5.291e+05
Df Model:                          31
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                     1025.4081    982.844      1.043      0.297    -901.021    2951.837
n_tokens_title                  48.6666     21.340      2.281      0.023       6.839      90.494
n_tokens_content                -0.5247      0.131     -4.008      0.000      -0.781      -0.268
n_non_stop_unique_tokens         7.8771     10.716      0.735      0.462     -13.127      28.881
num_hrefs                       42.6315      4.775      8.928      0.000      33.272      51.991
num_self_hrefs                 -55.0199     12.467     -4.413      0.000     -79.456     -30.583
num_imgs                        36.5750      6.032      6.063      0.000      24.752      48.398
num_videos                      17.1559     11.117      1.543      0.123      -4.633      38.945
average_token_length          -837.9062    164.887     -5.082      0.000   -1161.095    -514.718
num_keywords                   149.7973     26.724      5.605      0.000      97.416     202.179
kw_min_min                       2.6478      1.197      2.212      0.027       0.301       4.994
kw_max_min                      -0.0361      0.015     -2.414      0.016      -0.065      -0.007
kw_min_max                      -0.0025      0.001     -2.863      0.004      -0.004      -0.001
kw_max_max                      -0.0005      0.000     -1.084      0.278      -0.001       0.000
kw_avg_max                       0.0031      0.001      5.855      0.000       0.002       0.004
kw_min_avg                       0.1548      0.044      3.511      0.000       0.068       0.241
kw_max_avg                       0.0832      0.010      8.295      0.000       0.064       0.103
self_reference_avg_sharess       0.0128      0.002      7.140      0.000       0.009       0.016
LDA_01                         -49.2722    213.758     -0.231      0.818    -468.249     369.705
global_subjectivity           4434.7686    594.895      7.455      0.000    3268.741    5600.796
global_rate_positive_words   -1926.7871   3236.531     -0.595      0.552   -8270.569    4416.995
avg_positive_polarity         -371.0593    807.856     -0.459      0.646   -1954.503    1212.385
min_positive_polarity          -65.2270    811.878     -0.080      0.936   -1656.554    1526.100
max_positive_polarity           75.6728    313.062      0.242      0.809    -537.946     689.291
min_negative_polarity         -460.6741    183.356     -2.512      0.012    -820.062    -101.286
max_negative_polarity         -875.9709    486.162     -1.802      0.072   -1828.875      76.933
title_subjectivity             213.7489    205.986      1.038      0.299    -189.996     617.494
title_sentiment_polarity       654.2681    185.005      3.536      0.000     291.647    1016.889
abs_title_subjectivity         861.5931    272.856      3.158      0.002     326.780    1396.407
abs_title_sentiment_polarity   545.2446    296.749      1.837      0.066     -36.399    1126.889
data_channel                   105.0672     25.286      4.155      0.000      55.505     154.630
weekday_is                       5.7123     24.711      0.231      0.817     -42.724      54.148
==============================================================================
Omnibus:                    38064.341   Durbin-Watson:                   1.995
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         15755288.077
Skew:                           9.104   Prob(JB):                         0.00
Kurtosis:                     122.790   Cond. No.                     6.21e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.21e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [43]:
# Create a QQ plot for the residuals
sm.qqplot(no_multicol_model.resid, line='s');

#### Polynomial Regression

In [44]:
def polynomial_regression_summary(data, predictors, target, degree):
    # Construct the polynomial formula
    poly_formula = f'{target} ~ ' + ' + '.join([f'{col} + np.power({col}, {degree})' for col in predictors])
    
    # Fit the polynomial regression model
    poly_est = smf.ols(poly_formula, data).fit()
    
    # Return the fitted model
    return poly_est

#### Initial Polynomial Regression with All Predictors

In [45]:
degree = 2
polynomial_regression_summary(train_df, predictors, 'shares', degree).summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                       0.043
Model:                            OLS   Adj. R-squared:                  0.042
Method:                 Least Squares   F-statistic:                     47.71
Date:                Fri, 25 Apr 2025   Prob (F-statistic):          1.94e-221
Time:                        22:34:04   Log-Likelihood:            -2.6425e+05
No. Observations:               25756   AIC:                         5.286e+05
Df Residuals:                   25731   BIC:                         5.288e+05
Df Model:                          24
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                               1.211e+04   6088.454      1.989      0.047     174.676     2.4e+04
global_subjectivity                    -1644.6421   3028.141     -0.543      0.587   -7579.968    4290.684
np.power(global_subjectivity, 2)        5962.2570   3230.701      1.845      0.065    -370.099    1.23e+04
kw_max_avg                                 0.1012      0.012      8.178      0.000       0.077       0.125
np.power(kw_max_avg, 2)                -3.975e-07   9.66e-08     -4.113      0.000   -5.87e-07   -2.08e-07
num_hrefs                                 33.2455      6.969      4.771      0.000      19.587      46.904
np.power(num_hrefs, 2)                     0.0254      0.069      0.370      0.711      -0.109       0.160
self_reference_min_shares                  0.0709      0.005     14.113      0.000       0.061       0.081
np.power(self_reference_min_shares, 2) -1.047e-07   8.79e-09    -11.911      0.000   -1.22e-07   -8.75e-08
data_channel                            -228.5836    138.153     -1.655      0.098    -499.370      42.203
np.power(data_channel, 2)                 41.3909     16.429      2.519      0.012       9.189      73.592
num_imgs                                  33.9166     10.537      3.219      0.001      13.264      54.569
np.power(num_imgs, 2)                     -0.3318      0.202     -1.645      0.100      -0.727       0.064
average_token_length                   -4079.4339   2504.552     -1.629      0.103   -8988.497     829.629
np.power(average_token_length, 2)        357.5119    261.833      1.365      0.172    -155.695     870.719
num_self_hrefs                           -25.6834     18.693     -1.374      0.169     -62.322      10.955
np.power(num_self_hrefs, 2)               -0.1466      0.472     -0.311      0.756      -1.071       0.778
title_sentiment_polarity                 403.7566    176.308      2.290      0.022      58.182     749.331
np.power(title_sentiment_polarity, 2)   1021.8826    274.691      3.720      0.000     483.472    1560.293
kw_min_avg                                -1.0617      0.124     -8.582      0.000      -1.304      -0.819
np.power(kw_min_avg, 2)                    0.0005   4.36e-05     10.421      0.000       0.000       0.001
num_keywords                             362.2013    162.149      2.234      0.026      44.380     680.022
np.power(num_keywords, 2)                -19.6971     11.197     -1.759      0.079     -41.645       2.251
n_tokens_title                          -247.0095    149.314     -1.654      0.098    -539.674      45.655
np.power(n_tokens_title, 2)               14.5613      7.004      2.079      0.038       0.833      28.290
==============================================================================
Omnibus:                    38019.676   Durbin-Watson:                   1.995
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         15661143.279
Skew:                           9.084   Prob(JB):                         0.00
Kurtosis:                     122.429   Cond. No.                     1.68e+12
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.68e+12. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [46]:
degree = 3
polynomial_regression_summary(train_df, predictors, 'shares', degree).summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                       0.033
Model:                            OLS   Adj. R-squared:                  0.033
Method:                 Least Squares   F-statistic:                     80.46
Date:                Fri, 25 Apr 2025   Prob (F-statistic):          1.51e-179
Time:                        22:34:04   Log-Likelihood:            -2.6438e+05
No. Observations:               25756   AIC:                         5.288e+05
Df Residuals:                   25744   BIC:                         5.289e+05
Df Model:                          11
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                                  0.0269      0.009      3.056      0.002       0.010       0.044
global_subjectivity                        0.0416      0.003     12.184      0.000       0.035       0.048
np.power(global_subjectivity, 3)           0.0281      0.002     11.959      0.000       0.024       0.033
kw_max_avg                                 0.0931      0.009     10.372      0.000       0.076       0.111
np.power(kw_max_avg, 3)                 -9.02e-13   2.91e-13     -3.096      0.002   -1.47e-12   -3.31e-13
num_hrefs                                 40.9517      4.003     10.229      0.000      33.105      48.798
np.power(num_hrefs, 3)                    -0.0002      0.000     -1.020      0.308      -0.001       0.000
self_reference_min_shares                  0.0687      0.004     15.597      0.000       0.060       0.077
np.power(self_reference_min_shares, 3) -1.536e-13   1.17e-14    -13.118      0.000   -1.77e-13   -1.31e-13
data_channel                              -0.1572      0.041     -3.808      0.000      -0.238      -0.076
np.power(data_channel, 3)                  2.8798      0.385      7.475      0.000       2.125       3.635
num_imgs                                  13.5361      1.331     10.172      0.000      10.928      16.144
np.power(num_imgs, 3)                     -0.0008      0.001     -0.582      0.561      -0.004       0.002
average_token_length                       0.1698      0.044      3.835      0.000       0.083       0.257
np.power(average_token_length, 3)          5.2844      1.154      4.579      0.000       3.023       7.546
num_self_hrefs                             6.2244      0.604     10.299      0.000       5.040       7.409
np.power(num_self_hrefs, 3)               -0.0074      0.004     -1.890      0.059      -0.015       0.000
title_sentiment_polarity                   0.0509      0.005     10.622      0.000       0.041       0.060
np.power(title_sentiment_polarity, 3)      0.0319      0.003     10.262      0.000       0.026       0.038
kw_min_avg                                -0.4656      0.077     -6.057      0.000      -0.616      -0.315
np.power(kw_min_avg, 3)                 9.526e-08   8.75e-09     10.888      0.000    7.81e-08    1.12e-07
num_keywords                               0.2234      0.037      6.105      0.000       0.152       0.295
np.power(num_keywords, 3)                  0.8298      0.142      5.849      0.000       0.552       1.108
n_tokens_title                             0.1303      0.064      2.032      0.042       0.005       0.256
np.power(n_tokens_title, 3)                0.3621      0.054      6.725      0.000       0.257       0.468
==============================================================================
Omnibus:                    37893.976   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         15384049.627
Skew:                           9.029   Prob(JB):                         0.00
Kurtosis:                     121.360   Cond. No.                     6.75e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.75e+17. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [47]:
degree = 4
polynomial_regression_summary(train_df, predictors, 'shares', degree).summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                      -0.120
Model:                            OLS   Adj. R-squared:                 -0.120
Method:                 Least Squares   F-statistic:                    -917.0
Date:                Fri, 25 Apr 2025   Prob (F-statistic):               1.00
Time:                        22:34:05   Log-Likelihood:            -2.6627e+05
No. Observations:               25756   AIC:                         5.325e+05
Df Residuals:                   25752   BIC:                         5.326e+05
Df Model:                           3
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                               5.388e-16   2.12e-16      2.536      0.011    1.22e-16    9.55e-16
global_subjectivity                    -3.167e-12   1.25e-12     -2.536      0.011   -5.61e-12   -7.19e-13
np.power(global_subjectivity, 4)        1.993e-14   7.86e-15      2.536      0.011    4.53e-15    3.53e-14
kw_max_avg                              3.461e-12   1.36e-12      2.536      0.011    7.86e-13    6.14e-12
np.power(kw_max_avg, 4)                 2.383e-18   9.38e-19      2.542      0.011    5.45e-19    4.22e-18
num_hrefs                               1.249e-13   4.93e-14      2.536      0.011    2.84e-14    2.21e-13
np.power(num_hrefs, 4)                  2.133e-06   8.41e-07      2.536      0.011    4.85e-07    3.78e-06
self_reference_min_shares               9.073e-13   3.58e-13      2.536      0.011    2.06e-13    1.61e-12
np.power(self_reference_min_shares, 4)  1.312e-20   9.71e-21      1.351      0.177   -5.91e-21    3.22e-20
data_channel                            1.705e-15   6.72e-16      2.536      0.011    3.87e-16    3.02e-15
np.power(data_channel, 4)               2.603e-13   1.03e-13      2.536      0.011    5.91e-14    4.61e-13
num_imgs                                6.794e-15   2.68e-15      2.536      0.011    1.54e-15     1.2e-14
np.power(num_imgs, 4)                   8.904e-10   3.51e-10      2.536      0.011    2.02e-10    1.58e-09
average_token_length                    3.079e-15   1.21e-15      2.536      0.011    6.99e-16    5.46e-15
np.power(average_token_length, 4)        6.17e-13   2.43e-13      2.536      0.011     1.4e-13    1.09e-12
num_self_hrefs                          6.678e-15   2.63e-15      2.536      0.011    1.52e-15    1.18e-14
np.power(num_self_hrefs, 4)             1.253e-09   4.94e-10      2.536      0.011    2.85e-10    2.22e-09
title_sentiment_polarity                 2.79e-17    1.1e-17      2.536      0.011    6.34e-18    4.95e-17
np.power(title_sentiment_polarity, 4)   1.604e-17   6.33e-18      2.536      0.011    3.64e-18    2.84e-17
kw_min_avg                              5.989e-13   2.36e-13      2.536      0.011    1.36e-13    1.06e-12
np.power(kw_min_avg, 4)                 5.604e-11   1.28e-12     43.913      0.000    5.35e-11    5.85e-11
num_keywords                            4.588e-15   1.81e-15      2.536      0.011    1.04e-15    8.13e-15
np.power(num_keywords, 4)               2.913e-12   1.15e-12      2.536      0.011    6.62e-13    5.16e-12
n_tokens_title                          5.508e-15   2.17e-15      2.536      0.011    1.25e-15    9.76e-15
np.power(n_tokens_title, 4)             6.751e-12   2.66e-12      2.536      0.011    1.53e-12     1.2e-11
==============================================================================
Omnibus:                    37102.804   Durbin-Watson:                   1.813
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         13908757.618
Skew:                           8.681   Prob(JB):                         0.00
Kurtosis:                     115.512   Cond. No.                     3.17e+23
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.17e+23. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [48]:
degree = 5
polynomial_regression_summary(train_df, predictors, 'shares', degree).summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                      -0.131
Model:                            OLS   Adj. R-squared:                 -0.131
Method:                 Least Squares   F-statistic:                    -1494.
Date:                Fri, 25 Apr 2025   Prob (F-statistic):               1.00
Time:                        22:34:05   Log-Likelihood:            -2.6640e+05
No. Observations:               25756   AIC:                         5.328e+05
Df Residuals:                   25753   BIC:                         5.328e+05
Df Model:                           2
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                               5.663e-32   1.39e-33     40.697      0.000    5.39e-32    5.94e-32
global_subjectivity                    -1.001e-21   2.46e-23    -40.697      0.000   -1.05e-21   -9.53e-22
np.power(global_subjectivity, 5)       -8.289e-24   2.04e-25    -40.697      0.000   -8.69e-24   -7.89e-24
kw_max_avg                              4.293e-28   1.05e-29     40.697      0.000    4.09e-28     4.5e-28
np.power(kw_max_avg, 5)                 7.509e-24   3.17e-24      2.367      0.018    1.29e-24    1.37e-23
num_hrefs                               7.504e-31   1.84e-32     40.697      0.000    7.14e-31    7.87e-31
np.power(num_hrefs, 5)                  1.354e-23   3.33e-25     40.697      0.000    1.29e-23    1.42e-23
self_reference_min_shares               3.377e-28    8.3e-30     40.697      0.000    3.21e-28    3.54e-28
np.power(self_reference_min_shares, 5)  2.042e-26   1.47e-26      1.390      0.165   -8.37e-27    4.92e-26
data_channel                            2.597e-31   6.38e-33     40.697      0.000    2.47e-31    2.72e-31
np.power(data_channel, 5)               3.887e-28   9.55e-30     40.697      0.000     3.7e-28    4.07e-28
num_imgs                                3.651e-31   8.97e-33     40.697      0.000    3.48e-31    3.83e-31
np.power(num_imgs, 5)                   1.139e-24    2.8e-26     40.697      0.000    1.08e-24    1.19e-24
average_token_length                    2.653e-31   6.52e-33     40.697      0.000    2.52e-31    2.78e-31
np.power(average_token_length, 5)       1.335e-28   3.28e-30     40.697      0.000    1.27e-28     1.4e-28
num_self_hrefs                          1.862e-31   4.58e-33     40.697      0.000    1.77e-31    1.95e-31
np.power(num_self_hrefs, 5)             1.495e-25   3.67e-27     40.697      0.000    1.42e-25    1.57e-25
title_sentiment_polarity                5.238e-33   1.29e-34     40.697      0.000    4.99e-33    5.49e-33
np.power(title_sentiment_polarity, 5)   1.251e-33   3.07e-35     40.697      0.000    1.19e-33    1.31e-33
kw_min_avg                              1.676e-28   4.12e-30     40.697      0.000     1.6e-28    1.76e-28
np.power(kw_min_avg, 5)                 1.631e-14   4.01e-16     40.697      0.000    1.55e-14    1.71e-14
num_keywords                            3.577e-31   8.79e-33     40.697      0.000     3.4e-31    3.75e-31
np.power(num_keywords, 5)               1.269e-27   3.12e-29     40.697      0.000    1.21e-27    1.33e-27
n_tokens_title                          5.853e-31   1.44e-32     40.697      0.000    5.57e-31    6.14e-31
np.power(n_tokens_title, 5)             9.586e-27   2.36e-28     40.697      0.000    9.12e-27       1e-26
==============================================================================
Omnibus:                    37211.834   Durbin-Watson:                   1.787
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         14087045.465
Skew:                           8.729   Prob(JB):                         0.00
Kurtosis:                     116.234   Cond. No.                     1.68e+29
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.68e+29. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

#### Summary of Results & Analysis: Initial Polynomial Regression

The initial polynomial regression was performed using all available predictor variables. Degrees ranging from 2 to 5 were evaluated to find the best-fitting model. The highest achieved R-squared value was 0.043, which corresponded to a polynomial degree of 2. This modest improvement over the best R-squared value obtained from multilinear regression (0.038) suggested that polynomial terms helped capture some of the nonlinear trends in the data

#### Polynomial Regression without Multicollinearity

In [49]:
degree = 2
polynomial_regression_summary(train_df, predictors_wo_multicol, 'shares', degree).summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                       0.047
Model:                            OLS   Adj. R-squared:                  0.045
Method:                 Least Squares   F-statistic:                     22.34
Date:                Fri, 25 Apr 2025   Prob (F-statistic):          8.77e-223
Time:                        22:34:06   Log-Likelihood:            -2.6419e+05
No. Observations:               25756   AIC:                         5.285e+05
Df Residuals:                   25698   BIC:                         5.290e+05
Df Model:                          57
Covariance Type:            nonrobust
=============================================================================================================
                                                coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------
Intercept                                  1.174e+04   6016.840      1.952      0.051     -50.730    2.35e+04
n_tokens_title                             -230.4741    149.367     -1.543      0.123    -523.241      62.293
np.power(n_tokens_title, 2)                  13.8266      6.999      1.976      0.048       0.109      27.544
n_tokens_content                             -0.7623      0.266     -2.864      0.004      -1.284      -0.241
np.power(n_tokens_content, 2)                 0.0002   6.79e-05      3.000      0.003    7.06e-05       0.000
n_non_stop_unique_tokens                   1153.9377    633.539      1.821      0.069     -87.834    2395.710
np.power(n_non_stop_unique_tokens, 2)        -1.7621      0.974     -1.809      0.071      -3.672       0.147
num_hrefs                                    36.0516      7.482      4.819      0.000      21.387      50.716
np.power(num_hrefs, 2)                        0.0146      0.070      0.209      0.835      -0.123       0.152
num_self_hrefs                              -50.0088     18.904     -2.645      0.008     -87.061     -12.957
np.power(num_self_hrefs, 2)                   0.2249      0.474      0.475      0.635      -0.704       1.154
num_imgs                                     58.1537     11.812      4.923      0.000      35.001      81.306
np.power(num_imgs, 2)                        -0.6799      0.219     -3.106      0.002      -1.109      -0.251
num_videos                                   47.1148     19.798      2.380      0.017       8.310      85.919
np.power(num_videos, 2)                      -1.0595      0.500     -2.118      0.034      -2.040      -0.079
average_token_length                      -4602.9118   2521.982     -1.825      0.068   -9546.139     340.315
np.power(average_token_length, 2)           412.9766    263.701      1.566      0.117    -103.892     929.845
num_keywords                                194.1510    176.736      1.099      0.272    -152.261     540.563
np.power(num_keywords, 2)                    -7.2810     12.013     -0.606      0.544     -30.827      16.265
kw_min_min                                   13.9591     14.667      0.952      0.341     -14.790      42.708
np.power(kw_min_min, 2)                      -0.0530      0.066     -0.806      0.420      -0.182       0.076
kw_max_min                                   -0.1173      0.024     -4.856      0.000      -0.165      -0.070
np.power(kw_max_min, 2)                    1.525e-06   2.56e-07      5.963      0.000    1.02e-06    2.03e-06
kw_min_max                                   -0.0103      0.003     -3.631      0.000      -0.016      -0.005
np.power(kw_min_max, 2)                    7.503e-09   3.83e-09      1.961      0.050    1.74e-12     1.5e-08
kw_max_max                                    0.0012      0.001      1.028      0.304      -0.001       0.004
np.power(kw_max_max, 2)                   -1.277e-09   1.22e-09     -1.046      0.295   -3.67e-09    1.12e-09
kw_avg_max                                   -0.0007      0.002     -0.348      0.727      -0.005       0.003
np.power(kw_avg_max, 2)                    4.156e-09   2.94e-09      1.415      0.157    -1.6e-09    9.91e-09
kw_min_avg                                   -1.0743      0.127     -8.437      0.000      -1.324      -0.825
np.power(kw_min_avg, 2)                       0.0005   4.69e-05     10.160      0.000       0.000       0.001
kw_max_avg                                    0.1836      0.021      8.950      0.000       0.143       0.224
np.power(kw_max_avg, 2)                    -1.67e-06   2.47e-07     -6.769      0.000   -2.15e-06   -1.19e-06
self_reference_avg_sharess                    0.0443      0.004     12.007      0.000       0.037       0.052
np.power(self_reference_avg_sharess, 2)   -7.327e-08   7.46e-09     -9.824      0.000   -8.79e-08   -5.86e-08
LDA_01                                     -917.9807    703.962     -1.304      0.192   -2297.787     461.825
np.power(LDA_01, 2)                         931.7250    905.135      1.029      0.303    -842.391    2705.841
global_subjectivity                         553.9343   3247.757      0.171      0.865   -5811.853    6919.721
np.power(global_subjectivity, 2)           3127.3381   3436.177      0.910      0.363   -3607.762    9862.438
global_rate_positive_words                -3941.8216   3262.402     -1.208      0.227   -1.03e+04    2452.671
np.power(global_rate_positive_words, 2)    -383.4730    323.026     -1.187      0.235   -1016.621     249.675
avg_positive_polarity                     -2814.3819   3190.721     -0.882      0.378   -9068.376    3439.612
np.power(avg_positive_polarity, 2)         2534.8729   3924.548      0.646      0.518   -5157.463    1.02e+04
min_positive_polarity                     -1607.6553   1569.719     -1.024      0.306   -4684.393    1469.082
np.power(min_positive_polarity, 2)         1786.7249   3177.706      0.562      0.574   -4441.758    8015.207
max_positive_polarity                      1253.1561   1806.322      0.694      0.488   -2287.337    4793.649
np.power(max_positive_polarity, 2)         -738.6140   1172.102     -0.630      0.529   -3036.000    1558.772
min_negative_polarity                      -411.1483    643.966     -0.638      0.523   -1673.358     851.062
np.power(min_negative_polarity, 2)           50.8048    543.445      0.093      0.926   -1014.379    1115.988
max_negative_polarity                      -343.6140   1086.866     -0.316      0.752   -2473.933    1786.705
np.power(max_negative_polarity, 2)          554.2873   1640.744      0.338      0.735   -2661.663    3770.237
title_subjectivity                         3267.4514    871.499      3.749      0.000    1559.264    4975.639
np.power(title_subjectivity, 2)           -2934.8252    871.797     -3.366      0.001   -4643.596   -1226.054
title_sentiment_polarity                    651.5505    184.355      3.534      0.000     290.204    1012.897
np.power(title_sentiment_polarity, 2)      1449.9901    409.755      3.539      0.000     646.847    2253.133
abs_title_subjectivity                     3652.9724   1223.948      2.985      0.003    1253.966    6051.979
np.power(abs_title_subjectivity, 2)       -3260.7801   1554.659     -2.097      0.036   -6307.999    -213.562
abs_title_sentiment_polarity              -2000.4841    749.237     -2.670      0.008   -3469.031    -531.937
np.power(abs_title_sentiment_polarity, 2)  1449.9901    409.755      3.539      0.000     646.847    2253.133
data_channel                                 43.7705    148.397      0.295      0.768    -247.097     334.638
np.power(data_channel, 2)                     4.6444     17.581      0.264      0.792     -29.815      39.103
weekday_is                                 -412.0407    101.582     -4.056      0.000    -611.147    -212.934
np.power(weekday_is, 2)                      56.2178     13.263      4.239      0.000      30.221      82.215
==============================================================================
Omnibus:                    38036.304   Durbin-Watson:                   1.995
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         15782228.666
Skew:                           9.089   Prob(JB):                         0.00
Kurtosis:                     122.899   Cond. No.                     1.06e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.06e+16. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [50]:
degree = 3
polynomial_regression_summary(train_df, predictors_wo_multicol, 'shares', degree).summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                       0.028
Model:                            OLS   Adj. R-squared:                  0.027
Method:                 Least Squares   F-statistic:                     43.34
Date:                Fri, 25 Apr 2025   Prob (F-statistic):          1.96e-143
Time:                        22:34:06   Log-Likelihood:            -2.6445e+05
No. Observations:               25756   AIC:                         5.289e+05
Df Residuals:                   25738   BIC:                         5.291e+05
Df Model:                          17
Covariance Type:            nonrobust
=============================================================================================================
                                                coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------
Intercept                                    -0.0008      0.000     -2.591      0.010      -0.001      -0.000
n_tokens_title                                0.0004      0.001      0.691      0.490      -0.001       0.002
np.power(n_tokens_title, 3)                   0.2267      0.065      3.493      0.000       0.099       0.354
n_tokens_content                              0.0376      0.048      0.781      0.435      -0.057       0.132
np.power(n_tokens_content, 3)              8.368e-09    7.1e-09      1.179      0.238   -5.55e-09    2.23e-08
n_non_stop_unique_tokens                  -3.474e-06   7.32e-06     -0.475      0.635   -1.78e-05    1.09e-05
np.power(n_non_stop_unique_tokens, 3)      9.695e-06   2.54e-05      0.382      0.702      -4e-05    5.94e-05
num_hrefs                                     0.0004      0.001      0.668      0.504      -0.001       0.002
np.power(num_hrefs, 3)                        0.0007      0.000      3.329      0.001       0.000       0.001
num_self_hrefs                                0.0001      0.000      0.744      0.457      -0.000       0.000
np.power(num_self_hrefs, 3)                  -0.0011      0.004     -0.286      0.775      -0.009       0.007
num_imgs                                      0.0003      0.000      0.963      0.335      -0.000       0.001
np.power(num_imgs, 3)                         0.0014      0.002      0.902      0.367      -0.002       0.005
num_videos                                -2.858e-05      0.000     -0.157      0.875      -0.000       0.000
np.power(num_videos, 3)                    -2.27e-05      0.004     -0.005      0.996      -0.009       0.009
average_token_length                          0.0004      0.000      1.195      0.232      -0.000       0.001
np.power(average_token_length, 3)            -0.0006      0.000     -1.414      0.157      -0.001       0.000
num_keywords                                  0.0002      0.000      0.932      0.351      -0.000       0.001
np.power(num_keywords, 3)                     0.0371      0.045      0.825      0.409      -0.051       0.125
kw_min_min                                -2.256e-05    1.4e-05     -1.607      0.108   -5.01e-05    4.96e-06
np.power(kw_min_min, 3)                       0.0001    1.5e-05      8.795      0.000       0.000       0.000
kw_max_min                                   -0.1455      0.019     -7.489      0.000      -0.184      -0.107
np.power(kw_max_min, 3)                    1.703e-11   1.73e-12      9.844      0.000    1.36e-11    2.04e-11
kw_min_max                                   -0.0122      0.002     -5.836      0.000      -0.016      -0.008
np.power(kw_min_max, 3)                    8.702e-15   3.88e-15      2.244      0.025     1.1e-15    1.63e-14
kw_max_max                                    0.0023      0.001      4.094      0.000       0.001       0.003
np.power(kw_max_max, 3)                   -1.034e-15   7.26e-16     -1.425      0.154   -2.46e-15    3.88e-16
kw_avg_max                                   -0.0010      0.001     -0.914      0.361      -0.003       0.001
np.power(kw_avg_max, 3)                    7.458e-15   2.72e-15      2.742      0.006    2.13e-15    1.28e-14
kw_min_avg                                    0.0179      0.032      0.568      0.570      -0.044       0.080
np.power(kw_min_avg, 3)                    5.699e-08   6.25e-09      9.118      0.000    4.47e-08    6.92e-08
kw_max_avg                                    0.2142      0.014     14.976      0.000       0.186       0.242
np.power(kw_max_avg, 3)                   -1.736e-11   1.72e-12    -10.115      0.000   -2.07e-11    -1.4e-11
self_reference_avg_sharess                    0.0347      0.003     11.991      0.000       0.029       0.040
np.power(self_reference_avg_sharess, 3)   -8.743e-14   9.39e-15     -9.313      0.000   -1.06e-13    -6.9e-14
LDA_01                                     3.076e-06   5.42e-06      0.567      0.571   -7.55e-06    1.37e-05
np.power(LDA_01, 3)                        1.261e-06   3.55e-06      0.355      0.723    -5.7e-06    8.22e-06
global_subjectivity                        3.157e-06   1.05e-06      3.019      0.003    1.11e-06    5.21e-06
np.power(global_subjectivity, 3)           8.786e-07   1.95e-07      4.502      0.000    4.96e-07    1.26e-06
global_rate_positive_words                 2.959e-07   3.41e-07      0.867      0.386   -3.73e-07    9.65e-07
np.power(global_rate_positive_words, 3)    2.716e-10   1.14e-09      0.238      0.812   -1.96e-09    2.51e-09
avg_positive_polarity                      2.603e-06   1.29e-06      2.016      0.044    7.22e-08    5.13e-06
np.power(avg_positive_polarity, 3)         3.678e-07   1.45e-07      2.530      0.011    8.29e-08    6.53e-07
min_positive_polarity                     -1.387e-06    2.6e-06     -0.533      0.594   -6.49e-06    3.71e-06
np.power(min_positive_polarity, 3)        -2.696e-07   2.58e-07     -1.044      0.297   -7.76e-07    2.37e-07
max_positive_polarity                      1.337e-05    1.2e-05      1.111      0.267   -1.02e-05     3.7e-05
np.power(max_positive_polarity, 3)         1.896e-05   2.01e-05      0.942      0.346   -2.05e-05    5.84e-05
min_negative_polarity                     -1.582e-05   1.29e-05     -1.226      0.220   -4.11e-05    9.48e-06
np.power(min_negative_polarity, 3)        -1.544e-05   1.23e-05     -1.255      0.209   -3.95e-05    8.67e-06
max_negative_polarity                       1.42e-06   2.95e-06      0.481      0.631   -4.37e-06    7.21e-06
np.power(max_negative_polarity, 3)         2.953e-07   5.89e-07      0.502      0.616   -8.59e-07    1.45e-06
title_subjectivity                         1.015e-05   1.92e-06      5.277      0.000    6.38e-06    1.39e-05
np.power(title_subjectivity, 3)            2.266e-06   9.55e-07      2.373      0.018    3.94e-07    4.14e-06
title_sentiment_polarity                   2.937e-06   1.94e-06      1.510      0.131   -8.74e-07    6.75e-06
np.power(title_sentiment_polarity, 3)      8.727e-07   1.16e-06      0.753      0.452    -1.4e-06    3.15e-06
abs_title_subjectivity                    -6.453e-06   2.14e-06     -3.022      0.003   -1.06e-05   -2.27e-06
np.power(abs_title_subjectivity, 3)        -2.37e-06   7.18e-07     -3.301      0.001   -3.78e-06   -9.63e-07
abs_title_sentiment_polarity               5.841e-06   1.61e-06      3.636      0.000    2.69e-06    8.99e-06
np.power(abs_title_sentiment_polarity, 3)  1.154e-06   1.12e-06      1.028      0.304   -1.05e-06    3.35e-06
data_channel                               1.519e-05   1.89e-05      0.803      0.422   -2.19e-05    5.23e-05
np.power(data_channel, 3)                     0.0014      0.001      1.325      0.185      -0.001       0.004
weekday_is                                 3.514e-05   2.56e-05      1.370      0.171   -1.51e-05    8.54e-05
np.power(weekday_is, 3)                       0.0017      0.002      1.084      0.278      -0.001       0.005
==============================================================================
Omnibus:                    38084.245   Durbin-Watson:                   1.996
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         15769839.246
Skew:                           9.114   Prob(JB):                         0.00
Kurtosis:                     122.843   Cond. No.                     2.33e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.33e+16. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [51]:
degree = 4
polynomial_regression_summary(train_df, predictors_wo_multicol, 'shares', degree).summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                       0.005
Model:                            OLS   Adj. R-squared:                  0.005
Method:                 Least Squares   F-statistic:                     18.33
Date:                Fri, 25 Apr 2025   Prob (F-statistic):           1.62e-24
Time:                        22:34:07   Log-Likelihood:            -2.6475e+05
No. Observations:               25756   AIC:                         5.295e+05
Df Residuals:                   25748   BIC:                         5.296e+05
Df Model:                           7
Covariance Type:            nonrobust
=============================================================================================================
                                                coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------
Intercept                                    1.9e-08   9.17e-10     20.718      0.000    1.72e-08    2.08e-08
n_tokens_title                            -8.114e-09   3.94e-10    -20.596      0.000   -8.89e-09   -7.34e-09
np.power(n_tokens_title, 4)                 2.91e-10   1.45e-11     20.121      0.000    2.63e-10    3.19e-10
n_tokens_content                          -9.843e-11   5.07e-12    -19.430      0.000   -1.08e-10   -8.85e-11
np.power(n_tokens_content, 4)               1.62e-12   9.01e-13      1.798      0.072   -1.46e-13    3.39e-12
n_non_stop_unique_tokens                   1.508e-13   1.12e-13      1.351      0.177   -6.79e-14     3.7e-13
np.power(n_non_stop_unique_tokens, 4)      1.129e-08   3.95e-08      0.286      0.775   -6.62e-08    8.87e-08
num_hrefs                                  1.868e-12   9.36e-14     19.961      0.000    1.69e-12    2.05e-12
np.power(num_hrefs, 4)                     4.466e-11   3.47e-12     12.853      0.000    3.79e-11    5.15e-11
num_self_hrefs                            -3.603e-13   1.05e-12     -0.345      0.730   -2.41e-12    1.69e-12
np.power(num_self_hrefs, 4)                8.061e-11   1.75e-10      0.462      0.644   -2.61e-10    4.23e-10
num_imgs                                   2.919e-11   8.41e-11      0.347      0.729   -1.36e-10    1.94e-10
np.power(num_imgs, 4)                      1.063e-10    5.7e-12     18.662      0.000    9.52e-11    1.17e-10
num_videos                                 8.265e-16   3.99e-17     20.692      0.000    7.48e-16    9.05e-16
np.power(num_videos, 4)                    3.372e-11   1.63e-12     20.721      0.000    3.05e-11    3.69e-11
average_token_length                       3.204e-15   1.55e-16     20.637      0.000     2.9e-15    3.51e-15
np.power(average_token_length, 4)          3.302e-13    1.6e-14     20.636      0.000    2.99e-13    3.62e-13
num_keywords                               4.904e-15   2.38e-16     20.642      0.000    4.44e-15    5.37e-15
np.power(num_keywords, 4)                  2.494e-12   1.21e-13     20.661      0.000    2.26e-12    2.73e-12
kw_min_min                                 1.156e-13   5.58e-15     20.721      0.000    1.05e-13    1.27e-13
np.power(kw_min_min, 4)                    1.172e-06   5.65e-08     20.719      0.000    1.06e-06    1.28e-06
kw_max_min                                 8.779e-13   4.25e-14     20.636      0.000    7.94e-13    9.61e-13
np.power(kw_max_min, 4)                   -1.568e-17   1.06e-17     -1.479      0.139   -3.65e-17     5.1e-18
kw_min_max                                 5.544e-13   2.69e-14     20.641      0.000    5.02e-13    6.07e-13
np.power(kw_min_max, 4)                   -1.665e-20   2.87e-21     -5.790      0.000   -2.23e-20    -1.1e-20
kw_max_max                                 1.808e-10   8.83e-12     20.483      0.000    1.63e-10    1.98e-10
np.power(kw_max_max, 4)                    5.619e-21   1.17e-22     47.923      0.000    5.39e-21    5.85e-21
kw_avg_max                                 5.167e-11   2.52e-12     20.464      0.000    4.67e-11    5.66e-11
np.power(kw_avg_max, 4)                    6.858e-21   2.03e-21      3.376      0.001    2.88e-21    1.08e-20
kw_min_avg                                 3.356e-13   1.63e-14     20.614      0.000    3.04e-13    3.67e-13
np.power(kw_min_avg, 4)                    2.133e-11   1.49e-12     14.335      0.000    1.84e-11    2.42e-11
kw_max_avg                                 2.887e-12    1.4e-13     20.640      0.000    2.61e-12    3.16e-12
np.power(kw_max_avg, 4)                    1.745e-17   1.06e-17      1.651      0.099   -3.26e-18    3.82e-17
self_reference_avg_sharess                  2.08e-12   1.01e-13     20.656      0.000    1.88e-12    2.28e-12
np.power(self_reference_avg_sharess, 4)     2.91e-21   9.07e-21      0.321      0.748   -1.49e-20    2.07e-20
LDA_01                                     9.766e-17   4.73e-18     20.656      0.000    8.84e-17    1.07e-16
np.power(LDA_01, 4)                        2.309e-17   1.12e-18     20.647      0.000    2.09e-17    2.53e-17
global_subjectivity                        3.132e-16   1.52e-17     20.649      0.000    2.83e-16    3.43e-16
np.power(global_subjectivity, 4)           3.584e-17   1.74e-18     20.650      0.000    3.24e-17    3.92e-17
global_rate_positive_words                  3.08e-17   1.49e-18     20.647      0.000    2.79e-17    3.37e-17
np.power(global_rate_positive_words, 4)    5.642e-21   2.73e-22     20.646      0.000    5.11e-21    6.18e-21
avg_positive_polarity                      2.513e-16   1.22e-17     20.651      0.000    2.27e-16    2.75e-16
np.power(avg_positive_polarity, 4)         1.674e-17   8.11e-19     20.658      0.000    1.52e-17    1.83e-17
min_positive_polarity                      6.867e-17   3.33e-18     20.650      0.000    6.22e-17    7.52e-17
np.power(min_positive_polarity, 4)         7.641e-19   3.69e-20     20.689      0.000    6.92e-19    8.36e-19
max_positive_polarity                      5.296e-16   2.56e-17     20.651      0.000    4.79e-16     5.8e-16
np.power(max_positive_polarity, 4)         3.502e-16    1.7e-17     20.656      0.000    3.17e-16    3.83e-16
min_negative_polarity                     -3.249e-16   1.57e-17    -20.657      0.000   -3.56e-16   -2.94e-16
np.power(min_negative_polarity, 4)         1.166e-16   5.64e-18     20.672      0.000    1.06e-16    1.28e-16
max_negative_polarity                     -7.924e-17   3.84e-18    -20.648      0.000   -8.68e-17   -7.17e-17
np.power(max_negative_polarity, 4)         2.894e-18    1.4e-19     20.692      0.000    2.62e-18    3.17e-18
title_subjectivity                         1.803e-16   8.73e-18     20.660      0.000    1.63e-16    1.97e-16
np.power(title_subjectivity, 4)             7.25e-17   3.51e-18     20.655      0.000    6.56e-17    7.94e-17
title_sentiment_polarity                   6.002e-17    2.9e-18     20.683      0.000    5.43e-17    6.57e-17
np.power(title_sentiment_polarity, 4)      2.443e-17   1.18e-18     20.682      0.000    2.21e-17    2.67e-17
abs_title_subjectivity                     2.427e-16   1.18e-17     20.642      0.000     2.2e-16    2.66e-16
np.power(abs_title_subjectivity, 4)        2.525e-17   1.22e-18     20.636      0.000    2.29e-17    2.76e-17
abs_title_sentiment_polarity               1.029e-16   4.98e-18     20.668      0.000    9.31e-17    1.13e-16
np.power(abs_title_sentiment_polarity, 4)  2.443e-17   1.18e-18     20.682      0.000    2.21e-17    2.67e-17
data_channel                               2.921e-15   1.41e-16     20.646      0.000    2.64e-15     3.2e-15
np.power(data_channel, 4)                  4.856e-13   2.35e-14     20.663      0.000     4.4e-13    5.32e-13
weekday_is                                 2.291e-15   1.11e-16     20.645      0.000    2.07e-15    2.51e-15
np.power(weekday_is, 4)                    2.588e-13   1.25e-14     20.658      0.000    2.34e-13    2.83e-13
==============================================================================
Omnibus:                    38016.142   Durbin-Watson:                   1.992
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         15440541.436
Skew:                           9.090   Prob(JB):                         0.00
Kurtosis:                     121.564   Cond. No.                     5.02e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.02e+16. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [52]:
degree = 5
polynomial_regression_summary(train_df, predictors_wo_multicol, 'shares', degree).summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                      -0.015
Model:                            OLS   Adj. R-squared:                 -0.015
Method:                 Least Squares   F-statistic:                    -54.39
Date:                Fri, 25 Apr 2025   Prob (F-statistic):               1.00
Time:                        22:34:09   Log-Likelihood:            -2.6500e+05
No. Observations:               25756   AIC:                         5.300e+05
Df Residuals:                   25748   BIC:                         5.301e+05
Df Model:                           7
Covariance Type:            nonrobust
=============================================================================================================
                                                coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------
Intercept                                  9.542e-20   5.96e-21     16.015      0.000    8.37e-20    1.07e-19
n_tokens_title                             5.464e-19   3.42e-20     15.993      0.000    4.79e-19    6.13e-19
np.power(n_tokens_title, 5)                9.429e-20   5.89e-21     15.998      0.000    8.27e-20    1.06e-19
n_tokens_content                           3.295e-20   2.05e-21     16.050      0.000    2.89e-20     3.7e-20
np.power(n_tokens_content, 5)               2.19e-16   1.21e-16      1.809      0.070   -1.83e-17    4.56e-16
n_non_stop_unique_tokens                   6.092e-24   4.32e-25     14.098      0.000    5.24e-24    6.94e-24
np.power(n_non_stop_unique_tokens, 5)      1.254e-22   7.84e-24     15.995      0.000     1.1e-22    1.41e-22
num_hrefs                                  -1.55e-21   9.68e-23    -16.019      0.000   -1.74e-21   -1.36e-21
np.power(num_hrefs, 5)                    -1.122e-22   3.52e-23     -3.185      0.001   -1.81e-22   -4.31e-23
num_self_hrefs                             6.671e-33   1.25e-33      5.345      0.000    4.23e-33    9.12e-33
np.power(num_self_hrefs, 5)                5.225e-26   3.26e-27     16.027      0.000    4.59e-26    5.86e-26
num_imgs                                   7.788e-32   4.83e-33     16.134      0.000    6.84e-32    8.73e-32
np.power(num_imgs, 5)                      2.354e-25   5.42e-26      4.345      0.000    1.29e-25    3.42e-25
num_videos                                 6.361e-33   3.97e-34     16.031      0.000    5.58e-33    7.14e-33
np.power(num_videos, 5)                    3.787e-26   2.36e-27     16.068      0.000    3.32e-26    4.25e-26
average_token_length                       1.279e-32   7.99e-34     16.010      0.000    1.12e-32    1.44e-32
np.power(average_token_length, 5)          6.554e-30    4.1e-31     15.991      0.000    5.75e-30    7.36e-30
num_keywords                               5.043e-33   3.14e-34     16.039      0.000    4.43e-33    5.66e-33
np.power(num_keywords, 5)                  -1.13e-28   7.07e-30    -15.990      0.000   -1.27e-28   -9.92e-29
kw_min_min                                 2.997e-31   1.87e-32     16.017      0.000    2.63e-31    3.36e-31
np.power(kw_min_min, 5)                    6.621e-22   4.13e-23     16.018      0.000    5.81e-22    7.43e-22
kw_max_min                                 1.755e-29    1.1e-30     16.010      0.000    1.54e-29    1.97e-29
np.power(kw_max_min, 5)                   -7.914e-23   9.02e-23     -0.878      0.380   -2.56e-22    9.76e-23
kw_min_max                                 7.666e-28   4.79e-29     16.018      0.000    6.73e-28     8.6e-28
np.power(kw_min_max, 5)                   -2.031e-26   4.32e-27     -4.702      0.000   -2.88e-26   -1.18e-26
kw_max_max                                 1.294e-27   8.08e-29     16.014      0.000    1.14e-27    1.45e-27
np.power(kw_max_max, 5)                    6.886e-27   1.34e-28     51.541      0.000    6.62e-27    7.15e-27
kw_avg_max                                 1.232e-27   7.69e-29     16.012      0.000    1.08e-27    1.38e-27
np.power(kw_avg_max, 5)                    6.972e-27   3.34e-27      2.086      0.037    4.21e-28    1.35e-26
kw_min_avg                                 5.728e-29   3.58e-30     16.019      0.000    5.03e-29    6.43e-29
np.power(kw_min_avg, 5)                    7.269e-15   4.54e-16     16.018      0.000    6.38e-15    8.16e-15
kw_max_avg                                 6.758e-29   4.22e-30     16.016      0.000    5.93e-29    7.58e-29
np.power(kw_max_avg, 5)                    8.512e-23   9.01e-23      0.945      0.345   -9.15e-23    2.62e-22
self_reference_avg_sharess                  9.75e-29   6.09e-30     16.013      0.000    8.56e-29    1.09e-28
np.power(self_reference_avg_sharess, 5)    5.514e-27   1.39e-26      0.398      0.691   -2.17e-26    3.27e-26
LDA_01                                     8.152e-34   5.09e-35     16.019      0.000    7.15e-34    9.15e-34
np.power(LDA_01, 5)                        1.291e-34   8.04e-36     16.043      0.000    1.13e-34    1.45e-34
global_subjectivity                        2.163e-33   1.35e-34     16.019      0.000     1.9e-33    2.43e-33
np.power(global_subjectivity, 5)           4.125e-34   2.58e-35     16.017      0.000    3.62e-34    4.63e-34
global_rate_positive_words                 1.801e-34   1.12e-35     16.026      0.000    1.58e-34    2.02e-34
np.power(global_rate_positive_words, 5)    4.796e-39   2.99e-40     16.014      0.000    4.21e-39    5.38e-39
avg_positive_polarity                      1.632e-33   1.02e-34     16.023      0.000    1.43e-33    1.83e-33
np.power(avg_positive_polarity, 5)         1.386e-34   8.65e-36     16.022      0.000    1.22e-34    1.56e-34
min_positive_polarity                      5.277e-34    3.3e-35     15.985      0.000    4.63e-34    5.92e-34
np.power(min_positive_polarity, 5)         1.204e-35   7.52e-37     15.998      0.000    1.06e-35    1.35e-35
max_positive_polarity                       2.99e-33   1.86e-34     16.034      0.000    2.62e-33    3.36e-33
np.power(max_positive_polarity, 5)          3.16e-33   1.97e-34     16.054      0.000    2.77e-33    3.55e-33
min_negative_polarity                     -1.959e-33   1.22e-34    -16.063      0.000    -2.2e-33   -1.72e-33
np.power(min_negative_polarity, 5)        -1.183e-33   7.34e-35    -16.117      0.000   -1.33e-33   -1.04e-33
max_negative_polarity                     -5.393e-34   3.37e-35    -15.983      0.000   -6.05e-34   -4.73e-34
np.power(max_negative_polarity, 5)        -6.331e-35   3.96e-36    -16.004      0.000   -7.11e-35   -5.56e-35
title_subjectivity                         2.142e-33   1.34e-34     16.025      0.000    1.88e-33     2.4e-33
np.power(title_subjectivity, 5)            1.366e-33   8.53e-35     16.022      0.000     1.2e-33    1.53e-33
title_sentiment_polarity                   9.595e-34   5.98e-35     16.051      0.000    8.42e-34    1.08e-33
np.power(title_sentiment_polarity, 5)      3.452e-34   2.15e-35     16.040      0.000    3.03e-34    3.87e-34
abs_title_subjectivity                     8.025e-34   5.02e-35     16.000      0.000    7.04e-34    9.01e-34
np.power(abs_title_subjectivity, 5)        3.642e-35   2.28e-36     15.996      0.000     3.2e-35    4.09e-35
abs_title_sentiment_polarity               1.545e-33   9.64e-35     16.029      0.000    1.36e-33    1.73e-33
np.power(abs_title_sentiment_polarity, 5)  5.458e-34   3.41e-35     16.024      0.000    4.79e-34    6.13e-34
data_channel                               1.526e-32   9.54e-34     15.993      0.000    1.34e-32    1.71e-32
np.power(data_channel, 5)                  6.386e-29   3.99e-30     16.008      0.000     5.6e-29    7.17e-29
weekday_is                                 1.487e-32   9.27e-34     16.029      0.000     1.3e-32    1.67e-32
np.power(weekday_is, 5)                    2.306e-29   1.44e-30     16.048      0.000    2.02e-29    2.59e-29
==============================================================================
Omnibus:                    37434.595   Durbin-Watson:                   1.985
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         14285126.605
Skew:                           8.834   Prob(JB):                         0.00
Kurtosis:                     117.013   Cond. No.                     5.52e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.52e+16. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

#### Summary of Results & Analysis: Polynomial Regression without Multicollinearity

Considering the potential impact of multicollinearity on the model's stability and interpretability, polynomial regression was further conducted using predictor variables devoid of significant multicollinearity. This refinement yielded a slightly improved R-squared value of 0.047, again at a polynomial degree of 2. This is the best model so far overall.

#### Polynomial Regression with Focus on Significant Predictors

In [53]:
degree = 2
polynomial_regression_summary(train_df, significant_predictors, 'shares', degree).summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                       0.050
Model:                            OLS   Adj. R-squared:                  0.048
Method:                 Least Squares   F-statistic:                     29.78
Date:                Fri, 25 Apr 2025   Prob (F-statistic):          1.86e-244
Time:                        22:34:10   Log-Likelihood:            -2.6416e+05
No. Observations:               25756   AIC:                         5.284e+05
Df Residuals:                   25710   BIC:                         5.288e+05
Df Model:                          45
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                               6546.1275   5115.727      1.280      0.201   -3480.985    1.66e+04
n_tokens_title                          -221.2288    149.064     -1.484      0.138    -513.403      70.946
np.power(n_tokens_title, 2)               14.0240      6.985      2.008      0.045       0.333      27.715
n_non_stop_unique_tokens                1070.4089    536.801      1.994      0.046      18.248    2122.570
np.power(n_non_stop_unique_tokens, 2)     -1.6324      0.825     -1.978      0.048      -3.250      -0.015
num_hrefs                                 34.8143      7.245      4.805      0.000      20.614      49.015
np.power(num_hrefs, 2)                     0.0123      0.069      0.177      0.859      -0.124       0.148
num_self_hrefs                           -53.3351     19.432     -2.745      0.006     -91.423     -15.247
np.power(num_self_hrefs, 2)                0.1804      0.476      0.379      0.705      -0.753       1.113
num_imgs                                  35.2470     11.502      3.064      0.002      12.703      57.791
np.power(num_imgs, 2)                     -0.3294      0.205     -1.607      0.108      -0.731       0.072
average_token_length                   -2788.6795   2525.323     -1.104      0.269   -7738.454    2161.095
np.power(average_token_length, 2)        242.1319    263.573      0.919      0.358    -274.486     758.750
num_keywords                             165.8085    176.325      0.940      0.347    -179.799     511.416
np.power(num_keywords, 2)                 -6.7244     11.999     -0.560      0.575     -30.244      16.795
kw_max_min                                -0.0988      0.024     -4.068      0.000      -0.146      -0.051
np.power(kw_max_min, 2)                 1.226e-06   2.58e-07      4.743      0.000    7.19e-07    1.73e-06
kw_min_max                                -0.0084      0.003     -2.942      0.003      -0.014      -0.003
np.power(kw_min_max, 2)                 5.287e-09   3.79e-09      1.396      0.163   -2.14e-09    1.27e-08
kw_avg_max                                -0.0025      0.001     -2.206      0.027      -0.005      -0.000
np.power(kw_avg_max, 2)                 5.191e-09   2.02e-09      2.568      0.010    1.23e-09    9.15e-09
kw_min_avg                                -0.9266      0.128     -7.240      0.000      -1.177      -0.676
np.power(kw_min_avg, 2)                    0.0004   4.74e-05      8.749      0.000       0.000       0.001
kw_max_avg                                 0.1580      0.021      7.563      0.000       0.117       0.199
np.power(kw_max_avg, 2)                 -1.34e-06    2.5e-07     -5.354      0.000   -1.83e-06    -8.5e-07
self_reference_min_shares                  0.0503      0.006      8.413      0.000       0.039       0.062
np.power(self_reference_min_shares, 2) -7.768e-08   1.01e-08     -7.704      0.000   -9.74e-08   -5.79e-08
self_reference_max_shares                  0.0174      0.003      5.086      0.000       0.011       0.024
np.power(self_reference_max_shares, 2) -2.243e-08   5.18e-09     -4.327      0.000   -3.26e-08   -1.23e-08
LDA_00                                  2063.6183   1214.763      1.699      0.089    -317.385    4444.622
np.power(LDA_00, 2)                     -607.9834    835.151     -0.728      0.467   -2244.925    1028.959
LDA_01                                  -623.9579   1213.771     -0.514      0.607   -3003.017    1755.101
np.power(LDA_01, 2)                     2075.8829    935.555      2.219      0.027     242.143    3909.623
LDA_02                                  1580.1811   1226.646      1.288      0.198    -824.113    3984.476
np.power(LDA_02, 2)                    -1739.7186    793.442     -2.193      0.028   -3294.910    -184.527
LDA_03                                  3585.7763   1185.704      3.024      0.002    1261.729    5909.824
np.power(LDA_03, 2)                    -2610.5930    814.570     -3.205      0.001   -4207.196   -1013.990
LDA_04                                   -59.1264   1199.133     -0.049      0.961   -2409.495    2291.242
np.power(LDA_04, 2)                     1429.2461    766.622      1.864      0.062     -73.377    2931.869
global_subjectivity                     -851.3106   3056.340     -0.279      0.781   -6841.908    5139.287
np.power(global_subjectivity, 2)        3974.8778   3263.622      1.218      0.223   -2422.004    1.04e+04
title_sentiment_polarity                 454.7811    180.172      2.524      0.012     101.634     807.928
np.power(title_sentiment_polarity, 2)    959.4809    276.560      3.469      0.001     417.408    1501.554
abs_title_subjectivity                  3453.9365   1220.012      2.831      0.005    1062.644    5845.229
np.power(abs_title_subjectivity, 2)    -5162.4881   2122.937     -2.432      0.015   -9323.564   -1001.412
data_channel                             -42.9665    162.806     -0.264      0.792    -362.076     276.143
np.power(data_channel, 2)                 25.5592     19.726      1.296      0.195     -13.105      64.223
==============================================================================
Omnibus:                    38019.028   Durbin-Watson:                   1.994
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         15744550.053
Skew:                           9.081   Prob(JB):                         0.00
Kurtosis:                     122.755   Cond. No.                     2.47e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.47e+15. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [54]:
degree = 3
polynomial_regression_summary(train_df, significant_predictors, 'shares', degree).summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                       0.035
Model:                            OLS   Adj. R-squared:                  0.034
Method:                 Least Squares   F-statistic:                     54.23
Date:                Fri, 25 Apr 2025   Prob (F-statistic):          1.10e-181
Time:                        22:34:11   Log-Likelihood:            -2.6436e+05
No. Observations:               25756   AIC:                         5.288e+05
Df Residuals:                   25738   BIC:                         5.289e+05
Df Model:                          17
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                                  0.0090      0.001     10.679      0.000       0.007       0.011
n_tokens_title                            -0.0396      0.003    -11.661      0.000      -0.046      -0.033
np.power(n_tokens_title, 3)                0.3338      0.054      6.189      0.000       0.228       0.440
n_non_stop_unique_tokens                  -0.0008      0.001     -0.861      0.389      -0.003       0.001
np.power(n_non_stop_unique_tokens, 3)   1.269e-05   2.53e-05      0.502      0.616   -3.69e-05    6.23e-05
num_hrefs                                  0.0412      0.004      9.442      0.000       0.033       0.050
np.power(num_hrefs, 3)                     0.0007      0.000      3.447      0.001       0.000       0.001
num_self_hrefs                            -0.0009      0.001     -1.428      0.153      -0.002       0.000
np.power(num_self_hrefs, 3)               -0.0014      0.004     -0.361      0.718      -0.009       0.006
num_imgs                                   0.0140      0.002      8.885      0.000       0.011       0.017
np.power(num_imgs, 3)                      0.0023      0.001      1.627      0.104      -0.000       0.005
average_token_length                       0.0083      0.001     10.550      0.000       0.007       0.010
np.power(average_token_length, 3)          0.2730      0.029      9.468      0.000       0.217       0.330
num_keywords                               0.0114      0.001     12.763      0.000       0.010       0.013
np.power(num_keywords, 3)                  1.1867      0.135      8.811      0.000       0.923       1.451
kw_max_min                                -0.1133      0.019     -5.886      0.000      -0.151      -0.076
np.power(kw_max_min, 3)                 1.316e-11   1.74e-12      7.559      0.000    9.75e-12    1.66e-11
kw_min_max                                -0.0084      0.002     -4.013      0.000      -0.012      -0.004
np.power(kw_min_max, 3)                 6.661e-15   3.77e-15      1.766      0.077    -7.3e-16    1.41e-14
kw_avg_max                                 0.0022      0.001      3.870      0.000       0.001       0.003
np.power(kw_avg_max, 3)                 7.893e-17   1.97e-15      0.040      0.968   -3.78e-15    3.93e-15
kw_min_avg                                -0.4455      0.078     -5.677      0.000      -0.599      -0.292
np.power(kw_min_avg, 3)                 9.972e-08    9.3e-09     10.722      0.000    8.15e-08    1.18e-07
kw_max_avg                                 0.1762      0.015     12.110      0.000       0.148       0.205
np.power(kw_max_avg, 3)                -1.343e-11   1.73e-12     -7.758      0.000   -1.68e-11      -1e-11
self_reference_min_shares                  0.0500      0.005      9.901      0.000       0.040       0.060
np.power(self_reference_min_shares, 3) -1.188e-13   1.29e-14     -9.234      0.000   -1.44e-13   -9.36e-14
self_reference_max_shares                  0.0153      0.003      5.891      0.000       0.010       0.020
np.power(self_reference_max_shares, 3) -2.767e-14   5.58e-15     -4.963      0.000   -3.86e-14   -1.67e-14
LDA_00                                    -0.0025      0.000     -7.320      0.000      -0.003      -0.002
np.power(LDA_00, 3)                       -0.0015      0.000     -7.453      0.000      -0.002      -0.001
LDA_01                                    -0.0012      0.000     -7.375      0.000      -0.002      -0.001
np.power(LDA_01, 3)                       -0.0008      0.000     -7.580      0.000      -0.001      -0.001
LDA_02                                     0.0030      0.000      7.584      0.000       0.002       0.004
np.power(LDA_02, 3)                        0.0020      0.000      7.475      0.000       0.001       0.003
LDA_03                                     0.0018      0.000      7.856      0.000       0.001       0.002
np.power(LDA_03, 3)                        0.0012      0.000      7.648      0.000       0.001       0.002
LDA_04                                    -0.0005      0.000     -4.034      0.000      -0.001      -0.000
np.power(LDA_04, 3)                       -0.0004   8.27e-05     -4.535      0.000      -0.001      -0.000
global_subjectivity                        0.0003   2.64e-05     11.859      0.000       0.000       0.000
np.power(global_subjectivity, 3)           0.0002   1.39e-05     11.961      0.000       0.000       0.000
title_sentiment_polarity                  -0.0001   2.65e-05     -4.103      0.000      -0.000   -5.69e-05
np.power(title_sentiment_polarity, 3)  -3.925e-05   9.95e-06     -3.947      0.000   -5.87e-05   -1.98e-05
abs_title_subjectivity                     0.0003   2.42e-05     12.762      0.000       0.000       0.000
np.power(abs_title_subjectivity, 3)     6.829e-05   5.51e-06     12.388      0.000    5.75e-05    7.91e-05
data_channel                               0.0468      0.006      7.924      0.000       0.035       0.058
np.power(data_channel, 3)                  2.8964      0.377      7.688      0.000       2.158       3.635
==============================================================================
Omnibus:                    37828.111   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         15286844.354
Skew:                           8.999   Prob(JB):                         0.00
Kurtosis:                     120.986   Cond. No.                     8.05e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.05e+16. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [55]:
degree = 4
polynomial_regression_summary(train_df, significant_predictors, 'shares', degree).summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                      -0.102
Model:                            OLS   Adj. R-squared:                 -0.102
Method:                 Least Squares   F-statistic:                    -339.7
Date:                Fri, 25 Apr 2025   Prob (F-statistic):               1.00
Time:                        22:34:11   Log-Likelihood:            -2.6606e+05
No. Observations:               25756   AIC:                         5.321e+05
Df Residuals:                   25748   BIC:                         5.322e+05
Df Model:                           7
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                               1.808e-09   7.21e-10      2.508      0.012    3.95e-10    3.22e-09
n_tokens_title                          -2.72e-08   1.08e-08     -2.508      0.012   -4.85e-08   -5.94e-09
np.power(n_tokens_title, 4)             6.679e-09   2.66e-09      2.509      0.012    1.46e-09    1.19e-08
n_non_stop_unique_tokens                3.376e-09   1.33e-09      2.530      0.011    7.61e-10    5.99e-09
np.power(n_non_stop_unique_tokens, 4)   2.248e-08   4.15e-08      0.541      0.588   -5.89e-08    1.04e-07
num_hrefs                              -2.261e-10   8.99e-11     -2.514      0.012   -4.02e-10   -4.98e-11
np.power(num_hrefs, 4)                  2.093e-06   8.35e-07      2.508      0.012    4.57e-07    3.73e-06
num_self_hrefs                         -6.423e-15   2.57e-15     -2.503      0.012   -1.15e-14   -1.39e-15
np.power(num_self_hrefs, 4)             3.121e-09   1.25e-09      2.501      0.012    6.75e-10    5.57e-09
num_imgs                                5.518e-09    2.2e-09      2.508      0.012    1.21e-09    9.83e-09
np.power(num_imgs, 4)                   5.194e-09   2.07e-09      2.508      0.012    1.14e-09    9.25e-09
average_token_length                    2.541e-10   1.01e-10      2.508      0.012    5.55e-11    4.53e-10
np.power(average_token_length, 4)      -4.068e-12   1.62e-12     -2.508      0.012   -7.25e-12   -8.89e-13
num_keywords                            7.608e-14   3.03e-14      2.508      0.012    1.66e-14    1.36e-13
np.power(num_keywords, 4)               1.836e-11   7.32e-12      2.507      0.012    4.01e-12    3.27e-11
kw_max_min                              4.416e-12   1.76e-12      2.507      0.012    9.64e-13    7.87e-12
np.power(kw_max_min, 4)                -2.001e-17   1.12e-17     -1.780      0.075    -4.2e-17    2.02e-18
kw_min_max                             -6.508e-12    2.6e-12     -2.508      0.012   -1.16e-11   -1.42e-12
np.power(kw_min_max, 4)                -5.198e-20   2.92e-21    -17.794      0.000   -5.77e-20   -4.63e-20
kw_avg_max                              8.089e-10   3.23e-10      2.507      0.012    1.77e-10    1.44e-09
np.power(kw_avg_max, 4)                 3.822e-20   2.01e-21     18.967      0.000    3.43e-20    4.22e-20
kw_min_avg                              2.806e-12   1.12e-12      2.507      0.012    6.13e-13       5e-12
np.power(kw_min_avg, 4)                 4.346e-11    1.5e-12     28.985      0.000    4.05e-11    4.64e-11
kw_max_avg                              2.058e-11   8.21e-12      2.507      0.012    4.49e-12    3.67e-11
np.power(kw_max_avg, 4)                 2.199e-17   1.12e-17      1.963      0.050     3.4e-20    4.39e-17
self_reference_min_shares               1.151e-11   4.59e-12      2.507      0.012    2.51e-12    2.05e-11
np.power(self_reference_min_shares, 4)  5.176e-23   1.03e-20      0.005      0.996   -2.01e-20    2.02e-20
self_reference_max_shares               3.278e-11   1.31e-11      2.507      0.012    7.16e-12    5.84e-11
np.power(self_reference_max_shares, 4)  7.492e-21   3.57e-21      2.101      0.036    5.01e-22    1.45e-20
LDA_00                                  6.706e-16   2.67e-16      2.507      0.012    1.46e-16    1.19e-15
np.power(LDA_00, 4)                     1.959e-16   7.81e-17      2.507      0.012    4.27e-17    3.49e-16
LDA_01                                  7.637e-16   3.05e-16      2.507      0.012    1.67e-16    1.36e-15
np.power(LDA_01, 4)                     2.843e-16   1.13e-16      2.508      0.012    6.21e-17    5.07e-16
LDA_02                                  9.754e-16   3.89e-16      2.507      0.012    2.13e-16    1.74e-15
np.power(LDA_02, 4)                     3.399e-16   1.36e-16      2.507      0.012    7.42e-17    6.06e-16
LDA_03                                  6.957e-16   2.77e-16      2.507      0.012    1.52e-16    1.24e-15
np.power(LDA_03, 4)                     2.041e-16   8.14e-17      2.507      0.012    4.45e-17    3.64e-16
LDA_04                                  9.735e-16   3.88e-16      2.507      0.012    2.12e-16    1.73e-15
np.power(LDA_04, 4)                     3.321e-16   1.32e-16      2.507      0.012    7.25e-17    5.92e-16
global_subjectivity                     1.845e-15   7.36e-16      2.507      0.012    4.03e-16    3.29e-15
np.power(global_subjectivity, 4)        2.043e-16   8.15e-17      2.507      0.012    4.46e-17    3.64e-16
title_sentiment_polarity                2.711e-16   1.08e-16      2.507      0.012    5.92e-17    4.83e-16
np.power(title_sentiment_polarity, 4)    1.32e-16   5.26e-17      2.507      0.012    2.88e-17    2.35e-16
abs_title_subjectivity                   1.46e-15   5.82e-16      2.507      0.012    3.19e-16     2.6e-15
np.power(abs_title_subjectivity, 4)     1.541e-16   6.15e-17      2.507      0.012    3.36e-17    2.75e-16
data_channel                             1.68e-14    6.7e-15      2.507      0.012    3.67e-15    2.99e-14
np.power(data_channel, 4)               2.648e-12   1.06e-12      2.507      0.012    5.78e-13    4.72e-12
==============================================================================
Omnibus:                    36798.229   Durbin-Watson:                   1.846
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         13428138.609
Skew:                           8.548   Prob(JB):                         0.00
Kurtosis:                     113.546   Cond. No.                     2.38e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.38e+16. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [56]:
degree = 5
polynomial_regression_summary(train_df, significant_predictors, 'shares', degree).summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                      -0.120
Model:                            OLS   Adj. R-squared:                 -0.120
Method:                 Least Squares   F-statistic:                    -459.2
Date:                Fri, 25 Apr 2025   Prob (F-statistic):               1.00
Time:                        22:34:12   Log-Likelihood:            -2.6627e+05
No. Observations:               25756   AIC:                         5.326e+05
Df Residuals:                   25749   BIC:                         5.326e+05
Df Model:                           6
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                               9.602e-20   3.18e-21     30.188      0.000    8.98e-20    1.02e-19
n_tokens_title                         -1.202e-19   3.98e-21    -30.188      0.000   -1.28e-19   -1.12e-19
np.power(n_tokens_title, 5)            -6.842e-20   2.27e-21    -30.188      0.000   -7.29e-20    -6.4e-20
n_non_stop_unique_tokens               -3.779e-20   1.25e-21    -30.188      0.000   -4.02e-20   -3.53e-20
np.power(n_non_stop_unique_tokens, 5)  -1.449e-21    4.8e-23    -30.188      0.000   -1.54e-21   -1.36e-21
num_hrefs                               7.088e-23   2.35e-24     30.188      0.000    6.63e-23    7.55e-23
np.power(num_hrefs, 5)                  3.815e-23   1.26e-24     30.188      0.000    3.57e-23    4.06e-23
num_self_hrefs                          1.445e-23   4.79e-25     30.188      0.000    1.35e-23    1.54e-23
np.power(num_self_hrefs, 5)             1.365e-25   4.52e-27     30.188      0.000    1.28e-25    1.45e-25
num_imgs                                2.931e-31   9.71e-33     30.188      0.000    2.74e-31    3.12e-31
np.power(num_imgs, 5)                   9.151e-25   3.03e-26     30.188      0.000    8.56e-25    9.75e-25
average_token_length                    1.732e-31   5.74e-33     30.188      0.000    1.62e-31    1.84e-31
np.power(average_token_length, 5)       8.768e-29    2.9e-30     30.188      0.000     8.2e-29    9.34e-29
num_keywords                            2.488e-31   8.24e-33     30.188      0.000    2.33e-31    2.65e-31
np.power(num_keywords, 5)               1.006e-27   3.33e-29     30.188      0.000    9.41e-28    1.07e-27
kw_max_min                              6.761e-29   2.24e-30     30.188      0.000    6.32e-29     7.2e-29
np.power(kw_max_min, 5)                -1.277e-22   9.53e-23     -1.340      0.180   -3.14e-22    5.91e-23
kw_min_max                              1.486e-27   4.92e-29     30.188      0.000    1.39e-27    1.58e-27
np.power(kw_min_max, 5)                -6.777e-26   4.43e-27    -15.288      0.000   -7.65e-26   -5.91e-26
kw_avg_max                               1.01e-26   3.35e-28     30.188      0.000    9.44e-27    1.08e-26
np.power(kw_avg_max, 5)                 4.957e-26    3.4e-27     14.574      0.000    4.29e-26    5.62e-26
kw_min_avg                              1.332e-28   4.41e-30     30.188      0.000    1.25e-28    1.42e-28
np.power(kw_min_avg, 5)                 1.381e-14   4.58e-16     30.188      0.000    1.29e-14    1.47e-14
kw_max_avg                              2.949e-28   9.77e-30     30.188      0.000    2.76e-28    3.14e-28
np.power(kw_max_avg, 5)                 1.346e-22   9.53e-23      1.413      0.158   -5.21e-23    3.21e-22
self_reference_min_shares               2.557e-28   8.47e-30     30.188      0.000    2.39e-28    2.72e-28
np.power(self_reference_min_shares, 5)  2.923e-27   1.54e-26      0.190      0.849   -2.72e-26     3.3e-26
self_reference_max_shares               4.606e-28   1.53e-29     30.188      0.000    4.31e-28     4.9e-28
np.power(self_reference_max_shares, 5)   1.13e-26   4.75e-27      2.378      0.017    1.99e-27    2.06e-26
LDA_00                                  5.692e-33   1.89e-34     30.188      0.000    5.32e-33    6.06e-33
np.power(LDA_00, 5)                     1.343e-33   4.45e-35     30.188      0.000    1.26e-33    1.43e-33
LDA_01                                  6.159e-33   2.04e-34     30.188      0.000    5.76e-33    6.56e-33
np.power(LDA_01, 5)                     1.175e-33   3.89e-35     30.188      0.000     1.1e-33    1.25e-33
LDA_02                                  2.705e-33   8.96e-35     30.188      0.000    2.53e-33    2.88e-33
np.power(LDA_02, 5)                     2.435e-34   8.07e-36     30.188      0.000    2.28e-34    2.59e-34
LDA_03                                  1.464e-32   4.85e-34     30.188      0.000    1.37e-32    1.56e-32
np.power(LDA_03, 5)                     5.186e-33   1.72e-34     30.188      0.000    4.85e-33    5.52e-33
LDA_04                                  7.736e-33   2.56e-34     30.188      0.000    7.23e-33    8.24e-33
np.power(LDA_04, 5)                      2.02e-33   6.69e-35     30.188      0.000    1.89e-33    2.15e-33
global_subjectivity                     1.833e-32   6.07e-34     30.188      0.000    1.71e-32    1.95e-32
np.power(global_subjectivity, 5)        1.581e-33   5.24e-35     30.188      0.000    1.48e-33    1.68e-33
title_sentiment_polarity                3.876e-33   1.28e-34     30.188      0.000    3.62e-33    4.13e-33
np.power(title_sentiment_polarity, 5)   1.022e-33   3.39e-35     30.188      0.000    9.56e-34    1.09e-33
abs_title_subjectivity                  1.237e-32    4.1e-34     30.188      0.000    1.16e-32    1.32e-32
np.power(abs_title_subjectivity, 5)     6.172e-34   2.04e-35     30.188      0.000    5.77e-34    6.57e-34
data_channel                            1.645e-31   5.45e-33     30.188      0.000    1.54e-31    1.75e-31
np.power(data_channel, 5)               2.502e-28   8.29e-30     30.188      0.000    2.34e-28    2.66e-28
==============================================================================
Omnibus:                    36988.998   Durbin-Watson:                   1.808
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         13743321.043
Skew:                           8.630   Prob(JB):                         0.00
Kurtosis:                     114.841   Cond. No.                     4.03e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.03e+16. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

#### Run polynomial regression on 2nd iteration of statistically significant predictors

In [57]:
degree = 2
polynomial_regression_summary(train_df, significant_predictors2, 'shares', degree).summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                       0.043
Model:                            OLS   Adj. R-squared:                  0.042
Method:                 Least Squares   F-statistic:                     47.71
Date:                Fri, 25 Apr 2025   Prob (F-statistic):          1.94e-221
Time:                        22:34:12   Log-Likelihood:            -2.6425e+05
No. Observations:               25756   AIC:                         5.286e+05
Df Residuals:                   25731   BIC:                         5.288e+05
Df Model:                          24
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                               1.211e+04   6088.454      1.989      0.047     174.676     2.4e+04
kw_max_avg                                 0.1012      0.012      8.178      0.000       0.077       0.125
np.power(kw_max_avg, 2)                -3.975e-07   9.66e-08     -4.113      0.000   -5.87e-07   -2.08e-07
global_subjectivity                    -1644.6435   3028.144     -0.543      0.587   -7579.976    4290.689
np.power(global_subjectivity, 2)        5962.2589   3230.706      1.845      0.065    -370.107    1.23e+04
self_reference_min_shares                  0.0709      0.005     14.113      0.000       0.061       0.081
np.power(self_reference_min_shares, 2) -1.047e-07   8.79e-09    -11.911      0.000   -1.22e-07   -8.75e-08
num_hrefs                                 33.2455      6.969      4.771      0.000      19.587      46.904
np.power(num_hrefs, 2)                     0.0254      0.069      0.370      0.711      -0.109       0.160
data_channel                            -228.5836    138.153     -1.655      0.098    -499.370      42.203
np.power(data_channel, 2)                 41.3909     16.429      2.519      0.012       9.189      73.592
title_sentiment_polarity                 403.7566    176.308      2.290      0.022      58.182     749.331
np.power(title_sentiment_polarity, 2)   1021.8826    274.691      3.720      0.000     483.472    1560.293
num_self_hrefs                           -25.6834     18.693     -1.374      0.169     -62.322      10.955
np.power(num_self_hrefs, 2)               -0.1466      0.472     -0.311      0.756      -1.071       0.778
num_imgs                                  33.9166     10.537      3.219      0.001      13.264      54.569
np.power(num_imgs, 2)                     -0.3318      0.202     -1.645      0.100      -0.727       0.064
n_tokens_title                          -247.0095    149.314     -1.654      0.098    -539.674      45.655
np.power(n_tokens_title, 2)               14.5613      7.004      2.079      0.038       0.833      28.290
average_token_length                   -4079.4339   2504.552     -1.629      0.103   -8988.497     829.629
np.power(average_token_length, 2)        357.5119    261.833      1.365      0.172    -155.695     870.719
num_keywords                             362.2013    162.149      2.234      0.026      44.380     680.022
np.power(num_keywords, 2)                -19.6971     11.197     -1.759      0.079     -41.645       2.251
kw_min_avg                                -1.0617      0.124     -8.582      0.000      -1.304      -0.819
np.power(kw_min_avg, 2)                    0.0005   4.36e-05     10.421      0.000       0.000       0.001
==============================================================================
Omnibus:                    38019.676   Durbin-Watson:                   1.995
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         15661143.977
Skew:                           9.084   Prob(JB):                         0.00
Kurtosis:                     122.429   Cond. No.                     1.68e+12
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.68e+12. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [58]:
degree = 3
polynomial_regression_summary(train_df, significant_predictors2, 'shares', degree).summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                       0.033
Model:                            OLS   Adj. R-squared:                  0.033
Method:                 Least Squares   F-statistic:                     80.46
Date:                Fri, 25 Apr 2025   Prob (F-statistic):          1.51e-179
Time:                        22:34:13   Log-Likelihood:            -2.6438e+05
No. Observations:               25756   AIC:                         5.288e+05
Df Residuals:                   25744   BIC:                         5.289e+05
Df Model:                          11
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                                  0.0269      0.009      3.057      0.002       0.010       0.044
kw_max_avg                                 0.0931      0.009     10.372      0.000       0.076       0.111
np.power(kw_max_avg, 3)                 -9.02e-13   2.91e-13     -3.096      0.002   -1.47e-12   -3.31e-13
global_subjectivity                        0.0565      0.004     12.744      0.000       0.048       0.065
np.power(global_subjectivity, 3)           0.0279      0.002     11.909      0.000       0.023       0.033
self_reference_min_shares                  0.0687      0.004     15.597      0.000       0.060       0.077
np.power(self_reference_min_shares, 3) -1.535e-13   1.17e-14    -13.114      0.000   -1.76e-13   -1.31e-13
num_hrefs                                 40.9519      4.003     10.230      0.000      33.105      48.799
np.power(num_hrefs, 3)                    -0.0002      0.000     -1.020      0.308      -0.001       0.000
data_channel                              -0.1572      0.041     -3.808      0.000      -0.238      -0.076
np.power(data_channel, 3)                  2.8798      0.385      7.475      0.000       2.125       3.635
title_sentiment_polarity                   0.0509      0.005     10.622      0.000       0.041       0.060
np.power(title_sentiment_polarity, 3)      0.0319      0.003     10.262      0.000       0.026       0.038
num_self_hrefs                             6.2245      0.604     10.299      0.000       5.040       7.409
np.power(num_self_hrefs, 3)               -0.0074      0.004     -1.890      0.059      -0.015       0.000
num_imgs                                  13.5361      1.331     10.172      0.000      10.928      16.144
np.power(num_imgs, 3)                     -0.0008      0.001     -0.582      0.561      -0.004       0.002
n_tokens_title                             0.1303      0.064      2.032      0.042       0.005       0.256
np.power(n_tokens_title, 3)                0.3621      0.054      6.725      0.000       0.257       0.468
average_token_length                       0.1698      0.044      3.835      0.000       0.083       0.257
np.power(average_token_length, 3)          5.2844      1.154      4.579      0.000       3.023       7.546
num_keywords                               0.2234      0.037      6.105      0.000       0.152       0.295
np.power(num_keywords, 3)                  0.8298      0.142      5.849      0.000       0.552       1.108
kw_min_avg                                -0.4656      0.077     -6.057      0.000      -0.616      -0.315
np.power(kw_min_avg, 3)                 9.526e-08   8.75e-09     10.888      0.000    7.81e-08    1.12e-07
==============================================================================
Omnibus:                    37893.987   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         15384070.659
Skew:                           9.029   Prob(JB):                         0.00
Kurtosis:                     121.360   Cond. No.                     6.78e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.78e+17. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [59]:
degree = 4
polynomial_regression_summary(train_df, significant_predictors2, 'shares', degree).summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                      -0.120
Model:                            OLS   Adj. R-squared:                 -0.120
Method:                 Least Squares   F-statistic:                    -917.0
Date:                Fri, 25 Apr 2025   Prob (F-statistic):               1.00
Time:                        22:34:13   Log-Likelihood:            -2.6627e+05
No. Observations:               25756   AIC:                         5.325e+05
Df Residuals:                   25752   BIC:                         5.326e+05
Df Model:                           3
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                               5.388e-16   2.12e-16      2.536      0.011    1.22e-16    9.55e-16
kw_max_avg                              2.289e-11   9.03e-12      2.536      0.011     5.2e-12    4.06e-11
np.power(kw_max_avg, 4)                 2.383e-18   9.38e-19      2.542      0.011    5.45e-19    4.22e-18
global_subjectivity                     2.556e-16   1.01e-16      2.536      0.011    5.81e-17    4.53e-16
np.power(global_subjectivity, 4)        2.908e-17   1.15e-17      2.536      0.011     6.6e-18    5.15e-17
self_reference_min_shares               9.073e-13   3.58e-13      2.536      0.011    2.06e-13    1.61e-12
np.power(self_reference_min_shares, 4)  1.312e-20   9.71e-21      1.351      0.177   -5.91e-21    3.22e-20
num_hrefs                               1.249e-13   4.93e-14      2.536      0.011    2.84e-14    2.21e-13
np.power(num_hrefs, 4)                  2.133e-06   8.41e-07      2.536      0.011    4.85e-07    3.78e-06
data_channel                            1.706e-15   6.72e-16      2.536      0.011    3.87e-16    3.02e-15
np.power(data_channel, 4)               2.603e-13   1.03e-13      2.536      0.011    5.91e-14    4.61e-13
title_sentiment_polarity                 2.79e-17    1.1e-17      2.536      0.011    6.34e-18    4.95e-17
np.power(title_sentiment_polarity, 4)   1.604e-17   6.33e-18      2.536      0.011    3.64e-18    2.84e-17
num_self_hrefs                          6.678e-15   2.63e-15      2.536      0.011    1.52e-15    1.18e-14
np.power(num_self_hrefs, 4)             1.253e-09   4.94e-10      2.536      0.011    2.85e-10    2.22e-09
num_imgs                                6.794e-15   2.68e-15      2.536      0.011    1.54e-15     1.2e-14
np.power(num_imgs, 4)                   8.904e-10   3.51e-10      2.536      0.011    2.02e-10    1.58e-09
n_tokens_title                          5.508e-15   2.17e-15      2.536      0.011    1.25e-15    9.76e-15
np.power(n_tokens_title, 4)             6.751e-12   2.66e-12      2.536      0.011    1.53e-12     1.2e-11
average_token_length                    3.079e-15   1.21e-15      2.536      0.011    6.99e-16    5.46e-15
np.power(average_token_length, 4)        6.17e-13   2.43e-13      2.536      0.011     1.4e-13    1.09e-12
num_keywords                            4.588e-15   1.81e-15      2.536      0.011    1.04e-15    8.13e-15
np.power(num_keywords, 4)               2.913e-12   1.15e-12      2.536      0.011    6.62e-13    5.16e-12
kw_min_avg                              5.989e-13   2.36e-13      2.536      0.011    1.36e-13    1.06e-12
np.power(kw_min_avg, 4)                 5.604e-11   1.28e-12     43.913      0.000    5.35e-11    5.85e-11
==============================================================================
Omnibus:                    37102.804   Durbin-Watson:                   1.813
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         13908757.618
Skew:                           8.681   Prob(JB):                         0.00
Kurtosis:                     115.512   Cond. No.                     3.21e+23
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.21e+23. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [60]:
degree = 5
polynomial_regression_summary(train_df, significant_predictors2, 'shares', degree).summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 shares   R-squared:                      -0.131
Model:                            OLS   Adj. R-squared:                 -0.131
Method:                 Least Squares   F-statistic:                    -1494.
Date:                Fri, 25 Apr 2025   Prob (F-statistic):               1.00
Time:                        22:34:13   Log-Likelihood:            -2.6640e+05
No. Observations:               25756   AIC:                         5.328e+05
Df Residuals:                   25753   BIC:                         5.328e+05
Df Model:                           2
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                               5.663e-32   1.39e-33     40.697      0.000    5.39e-32    5.94e-32
kw_max_avg                             -1.194e-22   2.93e-24    -40.697      0.000   -1.25e-22   -1.14e-22
np.power(kw_max_avg, 5)                 7.509e-24   3.17e-24      2.367      0.018    1.29e-24    1.37e-23
global_subjectivity                     1.811e-30   4.45e-32     40.697      0.000    1.72e-30     1.9e-30
np.power(global_subjectivity, 5)        2.229e-33   5.48e-35     40.697      0.000    2.12e-33    2.34e-33
self_reference_min_shares               3.377e-28    8.3e-30     40.697      0.000    3.21e-28    3.54e-28
np.power(self_reference_min_shares, 5)  2.042e-26   1.47e-26      1.390      0.165   -8.37e-27    4.92e-26
num_hrefs                               7.504e-31   1.84e-32     40.697      0.000    7.14e-31    7.87e-31
np.power(num_hrefs, 5)                  1.354e-23   3.33e-25     40.697      0.000    1.29e-23    1.42e-23
data_channel                            2.597e-31   6.38e-33     40.697      0.000    2.47e-31    2.72e-31
np.power(data_channel, 5)               3.887e-28   9.55e-30     40.697      0.000     3.7e-28    4.07e-28
title_sentiment_polarity                5.238e-33   1.29e-34     40.697      0.000    4.99e-33    5.49e-33
np.power(title_sentiment_polarity, 5)   1.251e-33   3.07e-35     40.697      0.000    1.19e-33    1.31e-33
num_self_hrefs                          1.862e-31   4.58e-33     40.697      0.000    1.77e-31    1.95e-31
np.power(num_self_hrefs, 5)             1.495e-25   3.67e-27     40.697      0.000    1.42e-25    1.57e-25
num_imgs                                3.651e-31   8.97e-33     40.697      0.000    3.48e-31    3.83e-31
np.power(num_imgs, 5)                   1.139e-24    2.8e-26     40.697      0.000    1.08e-24    1.19e-24
n_tokens_title                          5.853e-31   1.44e-32     40.697      0.000    5.57e-31    6.14e-31
np.power(n_tokens_title, 5)             9.586e-27   2.36e-28     40.697      0.000    9.12e-27       1e-26
average_token_length                    2.653e-31   6.52e-33     40.697      0.000    2.52e-31    2.78e-31
np.power(average_token_length, 5)       1.335e-28   3.28e-30     40.697      0.000    1.27e-28     1.4e-28
num_keywords                            3.577e-31   8.79e-33     40.697      0.000     3.4e-31    3.75e-31
np.power(num_keywords, 5)               1.269e-27   3.12e-29     40.697      0.000    1.21e-27    1.33e-27
kw_min_avg                              1.676e-28   4.12e-30     40.697      0.000     1.6e-28    1.76e-28
np.power(kw_min_avg, 5)                 1.631e-14   4.01e-16     40.697      0.000    1.55e-14    1.71e-14
==============================================================================
Omnibus:                    37211.834   Durbin-Watson:                   1.787
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         14087045.465
Skew:                           8.729   Prob(JB):                         0.00
Kurtosis:                     116.234   Cond. No.                     1.67e+29
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.67e+29. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

#### Summary of Results & Analysis: Focus on Significant Predictors

Given the goal of identifying the most influential factors affecting article shares, polynomial regression was employed on the subset of significant predictor variables. Remarkably, this approach produced the highest R-squared value of the entire analysis: 0.050 at a polynomial degree of 2. This underscores the importance of focusing on key predictors to build a more concise and accurate model, although, this model is still not very accurate as the R-squared is closer to 0 than 1.

#### Summary of Results & Analysis: Polynomial Regression Overall

The application of polynomial regression provided valuable insights into the underlying relationships between predictor variables and the response variable. By flexibly accommodating nonlinear trends, this technique improved the model's predictive capability compared to the linear and multilinear regression approaches. The achieved R-squared values highlight the impact of careful predictor selection and the importance of accounting for nonlinearity in understanding the determinants of article shares. The highest R-squared achieved in this entire analysis was 0.05, which does mean that the model accuracy is not very good, as the model is significantly underfit.

### Discussion & Conclusion
In this study, my goal was to explore article sharing behavior in the digital landscape. I went into this project with the hope that I could construct a model that could be used to accurately predict the number of shares an article was likely to get. I explored every technique learned in class and some techniques that I taught myself. From the straightforward linear regression to the more sophisticated multilinear and polynomial regressions, I left no stone unturned in my quest for insights. Although I was not able to construct an accurate model, I did learn several new techniques that I hope to employ in future projects.


#### Learning and Takeaways
In the process of conducting this analysis, several valuable insights have been gleaned. The application of various regression techniques, including linear, multilinear, and polynomial regression, shed light on the complex relationship between predictor variables and article shares.

One key takeaway is the importance of careful predictor selection. Through rigorous analysis, it became evident that certain predictors have a significant impact on article shares. This emphasizes the need for a thoughtful approach to feature engineering, which ultimately enhances model performance.

Furthermore, the implementation of polynomial regression proved to be a crucial step in capturing nonlinear trends. This technique provided the flexibility to model intricate relationships that would have been missed by simpler linear models. By accommodating these nonlinearities, the model was able to make more accurate predictions and achieve a better fit to the data, although, it was ultimately underfit.